#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  These are the enchantment-specific error definitions.
##
##=head1 COPYRIGHT
##
##  Copyright 2009 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# ERROR definitions
#-------------------------------------------------------------------------------
# error codes
ERR_OK=0                  # everything is good
ERR_FATAL=1               # fatal error (missing cauldron libs, etc.)
ERR_STEP=2                # error in processing a step
ERR_LIBCOLOR=3            # problem loading libcolor when it was requested
ERR_MK_DIR=4              # couldn't make directory
ERR_DIR_EXISTS=5          # directory already exists
ERR_POTION_DIR=6          # potion directory is missing
ERR_GET_HASH_FILE=7       # problem generating file checksum
ERR_MK_HASH_FILE=8        # problem generating file checksum
ERR_GET_PARTITIONS=9      # couldn't read partitions
ERR_CHK_PARTITIONS=10     # couldn't store partitions
ERR_GET_FILESYSTEMS=11    # couldn't read filesystems
ERR_CHK_FILESYSTEMS=12    # couldn't store filesystems
ERR_GET_MOUNT_POINTS=13   # couldn't read mount points
ERR_CHK_MOUNT_POINTS=14   # couldn't store mount points
ERR_FILE_NOT_FOUND=15     # requested file not found
ERR_DIR_NOT_FOUND=16      # requested dir not found
ERR_CACHE_FILE=17         # couldn't copy file into potion dir
ERR_ARCHIVE_FORMAT=18     # unknown archive format
ERR_ARCHIVE=19            # could not build archive of potion
ERR_COMPRESS=20           # could not compress potion archive
ERR_MODULE_SCRIPT=21      # could not process module script
ERR_MODULE_ENTER=22       # could not process module entry
ERR_MODULE_EXIT=23        # could not process module exit

# lib.i18n keymap
ERR_KEYMAP_EXIT=50
ERR_KEYMAP_PREFIX=51
ERR_KEYMAP_LIST=52
ERR_KEYMAP_LIST_SIZE=53
ERR_KEYMAP_INPUT=54
ERR_KEYMAP_LOAD=55
ERR_KEYMAP_SAVE=56

# error messages
ERR_MSGS=(
          "operation succeeded"                             # ERR_OK
          "fatal error"                                     # ERR_FATAL
          "not a recognized step"                           # ERR_STEP
          "libcolor requested but couldn't load libcolor"   # ERR_LIBCOLOR
          "could not make directory"                        # ERR_MK_DIR
          "directory already exists"                        # ERR_DIR_EXISTS
          "potion directory is missing"                     # ERR_POTION_DIR
          "could not generate hashsum of file"              # ERR_MK_HASH_FILE
          "could not read partitions"                       # ERR_GET_PARTITIONS
          "could not store partitions"                      # ERR_CHK_PARTITIONS
          "could not read filesystems"                      # ERR_GET_FILESYSTEMS
          "could not store filesystems"                     # ERR_CHK_FILESYSTEMS
          "could not read mount points"                     # ERR_GET_MOUNT_POINTS
          "could not store mount points"                    # ERR_CHK_MOUNT_POINTS
          "file not found"                                  # ERR_FILE_NOT_FOUND
          "directory not found"                             # ERR_DIR_NOT_FOUND
          "could not cache file"                            # ERR_CACHE_FILE
          "unknown archive format"                          # ERR_ARCHIVE_FORMAT
          "could not create potion archive"                 # ERR_ARCHIVE
          "could not compress potion archive"               # ERR_COMPRESS
          "could not process module script"                 # ERR_MODULE_SCRIPT
          "could not process module entry"                  # ERR_MODULE_ENTER
          "could not process module exit"                   # ERR_MODULE_EXIT

          # lib.i18n keymap
          "keymap processing finished"                      # ERR_KEYMAP_EXIT
          "invalid keymap prefix"                           # ERR_KEYMAP_PREFIX
          "keymap list empty or not provided"               # ERR_KEYMAP_LIST
          "invalid list size provided"                      # ERR_KEYMAP_LIST_SIZE
          "invalid user input"                              # ERR_KEYMAP_INPUT
          "could not load selected keymap"                  # ERR_KEYMAP_LOAD
          "could not save selected keymap"                  # ERR_KEYMAP_SAVE
          )

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab

