#!/bin/bash
######################################################################
# Copyright 2004 by Kevin Dahan <unet@sourcemage.org>                #
######################################################################
#                                                                    #
#This program is free software; you can redistribute it and/or modify#
#it under the terms of the GNU General Public License as published by#
#the Free Software Foundation; either version 2 of the License, or   #
#(at your option) any later version.                                 #
#                                                                    #
#   This program is distributed in the hope that it will be useful,  #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of   #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    #
#   GNU General Public License for more details.                     #
#                                                                    #
# You should have received a copy of the GNU General Public License  #
# along with this program; if not, write to the Free Software        #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,              #
# MA  02111-1307  USA                                                #
######################################################################
# SMGL-HWD                                                           #
# Basic hardware detection script                                    #
# needs kudzu && hwdata                                              #
######################################################################

get_hw()
{
    echo "${NORMAL}Looking for ${BLUE}$CLASS${NORMAL} devices..."
    KUDZU=`kudzu -p -c $CLASS`
    DESC=`echo "$KUDZU" | grep 'desc'`
    MOD=`echo "$KUDZU" | grep driver`

    (( lim = `echo "$DESC" | wc -l` + 1 ))
    (( i = 1 ))

    while [ $i -ne $lim ]
      do  
      D=`echo "$DESC" | cut -d: -f2 | head -n $i | tail -n 1 | sed s/'"'//g`
      M=`echo "$MOD" | cut -d: -f2 | head -n $i | tail -n 1`

      if [ -n "$D" ] ;
	  then
	  if [ "$M" = " " ];
	      then
	      echo "$CLASS$i: $D * none" >>$CONFFILE
	  else
	      echo "$CLASS$i: $D * $M" >>$CONFFILE
	  fi
      fi

      (( i += 1 ))
    done
}

read_hw()
{
    (( lim = `cat $CONFFILE | grep $CLASS | wc -l` + 1 ))
    (( i = 1 ))
    while [ $i -ne $lim ]
      do
      NAME=`cat $CONFFILE | grep $CLASS | cut -d: -f2 | cut -d* -f1 | sed s/'  '// | head -n$i | tail -n1`
      MODULE=`cat $CONFFILE | grep $CLASS | cut -d: -f2 | cut -d* -f2 | sed s/'  '// | head -n$i | tail -n1`
      
      if [ $MODULE = 'none' ]
	  then 
	  echo "${RED}Cannot make ${BLUE}$NAME${RED} to work : Module not found !!!(${NORMAL}"
      else
	  echo "Activating ${BLUE}$NAME${NORMAL}..."
	  if [ $VERBOSE = 1 ] ;
	      then echo "${GREEN}Modprobe: ${BLUE}$MODULE${NORMAL}"
	  fi
	  modprobe $MODULE 2&1>/dev/null
      fi
      
      (( i += 1 ))
    done
}


tests()
{
    # Hotplug
    if [ -e /sbin/hotplug ] ;
	then 
	echo "${GREEN}Hotplug installed...${NORMAL}"
	HOTPLUG=1
    else 
	echo "${RED}Hotplug *NOT* installed! USB devices will *NOT* be probed!${NORMAL}"
	HOTPLUG=0
    fi

    if [ -e $CONFFILE ] ;
	then 
	SKIP_GET=1
    else
	SKIP_GET=0
    fi
}

flag() 
{
 if [ "$FLAG" = "help" ] ;
	then
	echo "add 'verbose' flag for more details"
	exit 0
    fi
    
    if [ "$FLAG" = "verbose" ] ;
	then 
	VERBOSE=1
	else
	VERBOSE=0
    fi
}

main ()
{

    flag &&
    tests &&


    if [ $HOTPLUG = 0 ];
	then 
	C='SCSI RAID NETWORK AUDIO'
    else 
	C='USB SCSI RAID NETWORK AUDIO'
    fi
    
    if [ $SKIP_GET = 0 ] ;
	then 
	echo "${GREEN}Auto-Detecing devices...${NORMAL}" &&
	
	for CLASS in `echo $C`
	  do get_hw
	done
    fi

    echo "${GREEN}Installing everything...${NORMAL}" &&

    for CLASS in `echo $C`
      do read_hw
    done

    echo "${GREEN}Your system is ready!${NORMAL}"
    
    exit 0
}


# Definitions
RED="[1;31m"
BLUE="[1;34m"
GREEN="[1;32m"
NORMAL="[0;39m"

CONFFILE=/tmp/smgl-hwd.conf

FLAG=$1

# Here it goes :p
main
