#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  These are the cauldron-specific error definitions.
##
##=head1 COPYRIGHT
##
##  Copyright 2009 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# ERROR definitions
#-------------------------------------------------------------------------------
# error codes
ERR_OK=0                  # everything is good
ERR_FATAL=1               # fatal error (missing cauldron libs, etc.)
ERR_ARCHIVE=2             # problem creating archives
ERR_CHROOT=3              # problem with a chroot
ERR_CLEANFILE=4           # missing cleaner files
ERR_TARGETSORCERY=5       # missing target sorcery files
ERR_HOSTSORCERY=6         # sorcery not installed on host

# error messages
ERR_MSGS=(
          "operation succeeded"                 # ERR_OK
          "fatal error"                         # ERR_FATAL
          "sorcery not set to archive"          # ERR_ARCHIVE
          "not in chroot"                       # ERR_CHROOT
          "cleanfile not found"                 # ERR_CLEANFILE
          "could not load target sorcery"       # ERR_TARGETSORCERY
          "could not load host sorcery"         # ERR_HOSTSORCERY
          )

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab

