#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  libcauldron is a set of functions used internally by the cauldron script
##
##=head1 COPYRIGHT
##
##  Copyright 2009 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
##
## Used only when checking initialization of the library and a fatal error
## occurs. Afterwards, functions from liberror should be used instead.
##
#-------------------------------------------------------------------------------
function cauldron_fatal_error() {
  echo $1
  exit $ERR_FATAL
}

#-------------------------------------------------------------------------------
##
## liberror includes - load these first!
##
#-------------------------------------------------------------------------------
. ${CAULDRON_BASE}/liberror 2>$CAULDRON_NULL ||
  cauldron_fatal_error "error: cannot load base libraries!"

# load cauldron error code and message defines
. ${CAULDRON_LIBS}/errorcodes 2>$CAULDRON_NULL ||
  cauldron_fatal_error "error: cannot load cauldron libraries!"

# drop cauldron_fatal_error if liberror was successfully loaded
unset cauldron_fatal_error

#-------------------------------------------------------------------------------
## @param library name to load (no path, just basename)
##
## Loads the library given as the first argument. liberror_check_fatal_error is
## called to check if there was a problem loading the library, and if there was
## it will print a corresponding error message and then exit with the error
## $ERR_LOAD_LIBRARY.
##
#-------------------------------------------------------------------------------
function cauldron_load_library() {
  local lib=$1

  . "$CAULDRON_LIBS/$lib" 2>$CAULDRON_NULL ||
  liberror_check_fatal_error
}

#-------------------------------------------------------------------------------
# cauldron includes
#-------------------------------------------------------------------------------
#cauldron_load_library lib.sorcerous

cauldron_load_library lib.chroot

cauldron_load_library lib.init

#cauldron_load_library lib.hostcache

if [[ $CAULDRON_COLOR == "yes" ]]
then
  . "$CAULDRON_BASE/libcolor"
  liberror_check_fatal_error
fi

#-------------------------------------------------------------------------------
##
## Scans the sorcery archspec files to find the host triplet
##
## Later, this will be used to set the value of HOST_TRIPLE in
## /etc/cauldron/config after the code to write the config file is in
## place
##
#-------------------------------------------------------------------------------
function cauldron_get_host_triple() {
  local HOST_ARCH
  local ARCH_SPEC
  local HOST_TRIPLE
  local SPEC_FILE

  # get the value for the HOST triplet from sorcery archspecs
  for spec in ${HOST_ARCH_PATH[@]}
  do
    if [[ $(find --version|grep -q 'version 4\.1\(\.\|$\)') == 1 ]]
    then
      ARCH_SPEC=$(find ${spec} -perm 400 -type f -name ${HOST_ARCH} \
        -print 2>/dev/null)
    else
      ARCH_SPEC=$(find -L ${spec} -perm 400 -type f -name ${HOST_ARCH} \
        -print 2>/dev/null)
    fi
    [[ ARCH_SPEC ]] && break
  done
  HOST_TRIPLE=$(grep "HOST=" ${ARCH_SPEC} | cut -d = -f 2)

  echo ${HOST_TRIPLE}
}

#-------------------------------------------------------------------------------
##
## Generates the base toolchain using the HOST information. This is
## done by unpacking the cache file for each spell required for the
## toolchain if it exists. If it does not exist, this may be because
## caching is disabled on the host machine, or perhaps the cache file
## was deleted by accident. Otherwise the spell must be cast within
## a chroot environment in the CAULDRON_BUILD directory.
##
#-------------------------------------------------------------------------------
function cauldron_base_toolchain() {
  local SPELL
  local VERSION
  local SPELL_CACHE
  local HOST_TRIPLE

  # set the value for HOST_TRIPLE
  HOST_TRIPLE=$(cauldron_get_host_triple)

  # grab the list of spells needed as the base tool-chain which will be
  # used to create the cross-compile tool-chain
  for SPELL in ${HOST_TOOLCHAIN}
  do
    # grab the version for the spell from sorcery's state info
    # on what's installed
    VERSION=$(grep "^${SPELL}" ${HOST_PACKAGES} | cut -d : -f 4)

    if [[ ${VERSION} ]]
    then
      # set SPELL_CACHE as shorthand for SPELL-VERSION-HOST_TRIPLE.tar.bz2
      SPELL_CACHE="${SPELL}-${VERSION}-${HOST_TRIPLE}.tar${CACHE_EXTENSION}"

      # check to see if there is already a cache file from sorcery
      # this check could be based on spell-{names,versions} reported by
      # gaze/sorcery/dispel. Mirroring code in dispel might be the best bet,
      # since that has to find the version currently installed anyway.
      if [[ -f "${HOST_SORCERY_SPOOL}/${SPELL_CACHE}" ]]
      then
        # found a cache file, copy it to the BUILD dir
        cp "${HOST_SORCERY_SPOOL}/${SPELL_CACHE}" "${CAULDRON_BUILD}"
      else
        # couldn't find a cache file, so we'll need to build one
        if [[ -z cauldron_build_host_cache_file ]]
        then
          cauldron_load_library lib.hostcache
        fi
        cauldron_build_host_cache_file ${SPELL}
      fi

      # unpack the cache file, effectively installing
      # the spell into the BUILD dir
      # the unpacking is done against the BUILD dir as the root dir, so
      # this should not touch the HOST filesystem at all
      tar xjf "${CAULDRON_BUILD}/${SPELL_CACHE}" -C "${CAULDRON_BUILD}"/
      [[ $? -eq 0 ]] && rm "${CAULDRON_BUILD}/${SPELL_CACHE}"
    else
      # the spell is not present on the HOST system, so it must be cast
      # inside a chroot
      cauldron_chroot ${CAULDRON_CAST} ${SPELL} || return $ERR_CHROOT
    fi
  done
}

#-------------------------------------------------------------------------------
## @param stage
##
## Configures the toolchain for building on the TARGET system. In other
## words, this sets the options/variables necessary to build a
## cross-compiler system to generate binaries for the target system. The
## parameter "stage" is an int and sets the variables for stage1 and stage2 of
## the cross-compile. Stage1 is the building of the initial tools. Stage2 is for
## the building of glibc, because it's a little bit special. Stage3 is
## the cross-compilation of the basesystem via sorcery rebuild using the
## cross-compiler.
##
#-------------------------------------------------------------------------------
function cauldron_configure_toolchain() {
  local stage=$1

  if [[ -z modify_config ]]
  then
    . "${SORCERY_LIBS}"/libtrack 2> $CAULDRON_NULL ||
      liberror_die $ERR_HOST_SORCERY
  fi

  case ${stage} in
    1)
      modify_config ${TARGET_LOCAL_CFG} CUSTOM_CFLAGS \
        "--host=${HOST} --target=${TARGET}"
    ;;
    2)
      modify_config ${TARGET_LOCAL_CFG} CUSTOM_CFLAGS \
        "--build=${HOST} --host=${TARGET}"
    ;;
    3)
      modify_config ${TARGET_LOCAL_CFG} CUSTOM_CFLAGS \
        "--build=${HOST} --host=${TARGET} --target=${TARGET}"
    ;;
  esac
}

#-------------------------------------------------------------------------------
##
## This builds the cross-compiler to produce the TARGET binaries.
##
#-------------------------------------------------------------------------------
function cauldron_cross_toolchain() {
  # build the stage 1 tools
  cauldron_configure_toolchain 1
  cauldron_chroot ${CAULDRON_CAST} binutils
  cauldron_chroot ${CAULDRON_CAST} gcc

  # build glibc (stage 2)
  cauldron_configure_toolchain 2
  cauldron_chroot ${CAULDRON_CAST} glibc

  # rebuild gcc (still stage 1, but this time linked against the
  # cross-glibc
  cauldron_configure_toolchain 1
  cauldron_chroot ${CAULDRON_CAST} gcc

  # do a sorcery rebuild inside the BUILD dir to
  # generate the cross-compile tool-chain (stage 3)
  cauldron_configure_toolchain 3
  cauldron_chroot ${CAULDRON_REBUILD}
}

#-------------------------------------------------------------------------------
## @param target_spells
##
## Performs cast on the list of spells needed for installation to the target
## system. "target_spells" is a list of spells that will be needed to install
## into the target system from the iso.
##
#-------------------------------------------------------------------------------
function cauldron_build_target_system() {
  local target_spells=$1
  local spell

  # Since we will be installing from the running ISO system instead of a giant
  # tarball, for each spell we only need to make sure that the cache file is
  # available. This will require that the ISO sorcery has caching enabled. The
  # caching should really be turned on from the very beginning though...
  [[ "$ARCHIVE" == "off" ]] && return $ERR_ARCHIVE

  for spell in $target_spells
  do
    # Cheap cop-out to get the cache generated - cast the spell to generate the
    # cache, and then dispel it from the system so that it isn't wasting space
    # on the ISO filesystem (any spells cast here should be those not required
    # for the functioning of the ISO itself, only to be installed to the target
    # system).
    cauldron_chroot ${CAULDRON_CAST} $spell
    cauldron_chroot ${CAULDRON_DISPEL} $spell
  done

  return $ERR_OK
}

#-------------------------------------------------------------------------------
## @param CLEANFILE
##
## Cleans out unneeded files that were used to generate the ISO, but should
## not be present on the final ISO system. CLEANFILE is a file that lists paths
## to remove (absolute paths, relative to a chroot of the iso), one file/path
## per line.
##
#-------------------------------------------------------------------------------
function cauldron_clean_iso_system() {
  local CLEANFILE=$1

  [[ -z "$CLEANFILE" ]] && return $ERR_CLEANFILE

  for i in $(sort -r $CLEANFILE)
  do
    if [[ -d $i ]]
    then
      echo "Attempting to remove directory $i..."
      rmdir $i
    else
      echo "Deleting $i"
      rm $i
    fi
  done
  return $ERR_OK
}

#-------------------------------------------------------------------------------
## @param KEEP - whether or not to keep the original .iso file in addition to
## the compressed .iso.bz2
##
## Builds the ISO filesystem using the generated ISO data and the filename
## set in the cauldron config file.
##
#-------------------------------------------------------------------------------
function cauldron_mkisofs() {
  mkisofs -R -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot \
    -boot-load-size 4 -boot-info-table -o ${SMGL_ISO} ${CAULDRON_BUILD}

  if [[ "$CAULDRON_KEEPISO" == "yes" ]] ;
  then
    bzip2 -k ${SMGL_ISO}
  else
    bzip2 ${SMGL_ISO}
  fi
}

#-------------------------------------------------------------------------------
## @param INSTALLER_MODULE
##
## Adds the given installer to the ISO system. The user can then choose this
## installer either at boot-time or run-time, depending on the installer.
## INSTALLER_MODULE is currently one of shell or menu (future: X?). In theory it
## should support any installer, as long as it's packaged in its own directory and
## the name of that dir is passed as the arg. This behavior may change in the
## future though.
##
#-------------------------------------------------------------------------------
function cauldron_add_installer() {
  local MODULE=$1

  cp -r "$CAULDRON_LIBS/$MODULE" "$CAULDRON_BUILD/$ENCHANT_DATA/"
  ln -sf "$CAULDRON_BUILD/$ENCHANT_DATA/$MODULE"/bin/* \
          "$CAULDRON_BUILD"/usr/sbin/
}

#-------------------------------------------------------------------------------
##
## This creates the CAULDRON_BUILD directory, and copies sorcery and
## cauldron files into it. It also configures the CAULDRON_BUILD
## sorcery as necessary (i.e. ensures that CLEAN_SOURCE="off") for
## sanity purposes
##
#-------------------------------------------------------------------------------
function cauldron_prepare() {
  # ensure that the build dir exists
  mkdir -p "$CAULDRON_BUILD"

  # copy the host's resolv.conf in order to dl packages from net
  cp -L /etc/resolv.conf "$CAULDRON_BUILD"/etc/resolv.conf

  # install sorcery into the build dir
  if [[ -z cauldron_sorcery_install ]]
  then
    cauldron_load_library lib.sorcerous
  fi
  cauldron_sorcery_install "$CAULDRON_BUILD" || return $ERR_SORCERY_INSTALL

  # cauldron is a spell
  # there is a spoon
  cauldron_chroot "$CAULDRON_CAST" cauldron || return $ERR_CHROOT

  return $ERR_OK
}

#-------------------------------------------------------------------------------
##
## Cleans up the tmp directories and such forth
##
#-------------------------------------------------------------------------------
function cauldron_cleanup() {
  # if the user wants everything cleaned, kill the build directory
  if [[ ${CAULDRON_CLEAN} == "yes" ]]
  then
    rm -fr "$CAULDRON_BUILD" || return $ERR_CLEANUP
  fi

  # kill the temp directory
  rm -fr "$CAULDRON_TMP" || return $ERR_CLEANUP

  return $ERR_OK
}

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
