#!/bin/bash

# path to the ISO system (this should usually be null, unless
# you are doing some tricky hacking)
      ENCHANT_ISO_PATH="${ENCHANT_ISO_PATH:-}"
# path to the enchant library modules
          ENCHANT_BASE="${ENCHANT_BASE:-$ENCHANT_ISO_PATH/var/lib/cauldron/}"
          ENCHANT_LIBS="${ENCHANT_LIBS:-$ENCHANT_BASE/enchantment}"
           ENCHANT_TMP="${ENCHANT_TMP:-$ENCHANT_ISO_PATH/tmp/enchantment}"
        ENCHANT_STATUS="${ENCHANT_STATUS:-$ENCHANT_TMP/status}"
          ENCHANT_BACK="${ENCHANT_BACK:-$ENCHANT_TMP/history/back}"
       ENCHANT_FORWARD="${ENCHANT_FORWARD:-$ENCHANT_TMP/history/forward}"
        ENCHANT_TARGET="${ENCHANT_TARGET:-$ENCHANT_ISO_PATH/mnt/root}"
          ENCHANT_DATA="${ENCHANT_DATA:-$ENCHANT_ISO_PATH/usr/share/enchantment}"
       ENCHANT_MODULES="${ENCHANT_MODULES:-$ENCHANT_DATA/modules}"
          ENCHANT_DOCS="${ENCHANT_DOCS:-$ENCHANT_ISO_PATH/usr/share/doc/enchantment}"

# whether to use color for displaying messages
         ENCHANT_COLOR="${ENCHANT_COLOR:-yes}"

# size of history buffers, total size = $ENCHANT_HISTORY * 2 = (back + forward)
       ENCHANT_HISTORY=${ENCHANT_HISTORY:-20}

ENCHANT_SORCERY_CONFIG="${ENCHANT_SORCERY_CONFIG:-/etc/sorcery/config}"
  ENCHANT_SORCERY_LIBS="${ENCHANT_SORCERY_LIBS:-/var/lib/sorcery/modules}"
# branch of sorcery to use in the ISO
ENCHANT_SORCERY_BRANCH="${ENCHANT_SORCERY_BRANCH:-stable}"

        HOST_ARCH_PATH=$(grep "ARCH_SPEC=" ${SORCERY_CONFIG} | \
                         cut -d = -f 2)
             HOST_ARCH=$(grep "ARCHITECTURE=" ${HOST_SORCERY_CONFIG} | \
                         cut -d = -f 2)
       CACHE_EXTENSION=$(grep "EXTENSION=" ${HOST_SORCERY_CONFIG} | \
                         cut -d = -f 2)

