#!/bin/bash

      # path to the ISO system (this should usually be null, unless
      # you are doing some tricky hacking)
      ENCHANT_ISO_PATH="${ENCHANT_ISO_PATH:-}"

          # path to the enchant library modules
          ENCHANT_BASE="${ENCHANT_BASE:-$ENCHANT_ISO_PATH/var/lib/cauldron}"
          ENCHANT_LIBS="${ENCHANT_LIBS:-$ENCHANT_BASE/enchantment}"

          # where the installer files are located
          ENCHANT_DATA="${ENCHANT_DATA:-$ENCHANT_ISO_PATH/usr/share/enchantment}"
       # location of the install modules (steps)
       ENCHANT_MODULES="${ENCHANT_MODULES:-$ENCHANT_DATA/modules}"
          # location of installer documentation
          ENCHANT_DOCS="${ENCHANT_DOCS:-$ENCHANT_ISO_PATH/usr/share/doc/enchantment}"

           # temp directory used during the install
           ENCHANT_TMP="${ENCHANT_TMP:-$ENCHANT_ISO_PATH/tmp/enchantment}"

        # path where potion state data is stored
        ENCHANT_POTION="${ENCHANT_POTION:-$ENCHANT_TMP/potion}"

        # where the target system is mounted
        ENCHANT_TARGET="${ENCHANT_TARGET:-$ENCHANT_ISO_PATH/mnt/root}"

 # absolute path to the file which the kernel should be installed as
 ENCHANT_TARGET_KERNEL="${ENCHANT_TARGET_KERNEL:-$ENCHANT_TARGET/boot/vmlinuz}"
  # path where kernel modules should be installed
  ENCHANT_TARGET_KMODS="${ENCHANT_TARGET_KMODS:-$ENCHANT_TARGET/lib/modules}"

# path where spell sources will be installed
ENCHANT_TARGET_SOURCES="${ENCHANT_TARGET_SOURCES:-$ENCHANT_TARGET/var/spool/sorcery}"
 # path where spell caches will be installed
 ENCHANT_TARGET_CACHES="${ENCHANT_TARGET_CACHES:-$ENCHANT_TARGET/var/cache/sorcery}"

        # command to chroot to ENCHANT_TARGET
        ENCHANT_CHROOT="${ENCHANT_CHROOT:-$ENCHANT_ISO_PATH/bin/chroot}"

 # path to installable spell sources
 ENCHANT_SPELL_SOURCES="${ENCHANT_SPELL_SOURCES:-$ENCHANT_ISO_PATH/var/spool/sorcery}"
  # path to installable spell caches (pre-built binaries)
  ENCHANT_SPELL_CACHES="${ENCHANT_SPELL_CACHES:-$ENCHANT_ISO_PATH/var/cache/sorcery}"
  # file to hold sources selected for install
  ENCHANT_SOURCES_LIST="${ENCHANT_SOURCES_LIST:-$ENCHANT_TMP/spell-sources}"
   # file to hold caches selected for install
   ENCHANT_CACHES_LIST="${ENCHANT_CACHES_LIST:-$ENCHANT_TMP/spell-caches}"

        # install module (step) info
        ENCHANT_STATUS="${ENCHANT_STATUS:-$ENCHANT_TMP/current_module}"

        # user-selected keymap
        ENCHANT_KEYMAP="${ENCHANT_KEYMAP:-$ENCHANT_TMP/i18n-keymap}"

       # install module history settings
       ENCHANT_HISTORY="${ENCHANT_HISTORY:-$ENCHANT_TMP/history}"
          ENCHANT_BACK="${ENCHANT_BACK:-$ENCHANT_HISTORY/back}"
       ENCHANT_FORWARD="${ENCHANT_FORWARD:-$ENCHANT_HISTORY/forward}"
  # size of history buffers, total size = $ENCHANT_HISTORY * 2 = (back + forward)
  ENCHANT_HISTORY_SIZE="${ENCHANT_HISTORY_SIZE:-20}"

      # path where potion state data is stored
      ENCHANT_HASHFUNC="${ENCHANT_HASHFUNC:-$ENCHANT_ISO_PATH/bin/sha1sum}"

       # path where potion state data is stored
       ENCHANT_ARCHIVE="${ENCHANT_ARCHIVE:-$ENCHANT_ISO_PATH/bin/tar}"
      # path where potion state data is stored
      ENCHANT_COMPRESS="${ENCHANT_COMPRESS:-$ENCHANT_ISO_PATH/bin/gzip}"

         # whether to use color for displaying messages
         ENCHANT_COLOR="${ENCHANT_COLOR:-yes}"

     # kernel version to use for installs
     ENCHANT_ISO_KVERS="${ENCHANT_ISO_KVERS:-$(uname -r)}"
    # kernel image to use for installs
    ENCHANT_ISO_KERNEL="${ENCHANT_ISO_KERNEL:-$ENCHANT_ISO_PATH/boot/vmlinux}"
     # path to the kernel modules to use for the install
     ENCHANT_ISO_KMODS="${ENCHANT_ISO_KMODS:-$ENCHANT_ISO_PATH/lib/modules}"

# branch of sorcery to use in the ISO
ENCHANT_SORCERY_BRANCH="${ENCHANT_SORCERY_BRANCH:-stable}"

# ISO sorcery config paths
ENCHANT_SORCERY_CONFIG="${ENCHANT_SORCERY_CONFIG:-$ENCHANT_ISO_PATH/etc/sorcery/config}"
  ENCHANT_SORCERY_LIBS="${ENCHANT_SORCERY_LIBS:-$ENCHANT_ISO_PATH/var/lib/sorcery/modules}"

# ISO architecture/machine/host information (used to select caches when more
# than one architecture is available for caches)
ENCHANT_HOST_ARCH_PATH="${ENCHANT_HOST_ARCH_PATH:-$ENCHANT_ISO_PATH/usr/share/archspecs}"
          # list of archs available for install on this ISO, if undefined set to
          # the first entry in the archs file written by cauldron at generation
          ENCHANT_ARCH="${ENCHANT_ARCH:-$(head -n1 $ENCHANT_DATA/archs)}"
      ENCHANT_MACHTYPE="${ENCHANT_HOST_ARCH:-$MACHTYPE}"
     ENCHANT_CACHE_EXT="${ENCHANT_CACHE_EXT:-tar.bz2}"


# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
