#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  liberror is a set of functions and variable definitions used
##  internally by cauldron for error handling and error definitions
##
##=head1 COPYRIGHT
##
##  Copyright 2007 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Local global variables
#-------------------------------------------------------------------------------
CDEFAULT_COLOR="\e[0m"
CBOLD="\e[1m"
CBLACK="\e[30m"
CRED="\e[31m"
CGREEN="\e[32m"
CYELLOW="\e[33m"
CBLUE="\e[34m"
CVIOLET="\e[35m"
CCYAN="\e[36m"
CWHITE="\e[37m"

CERR_COLOR="${RED}${BOLD}"
EERR_COLOR="${RED}${BOLD}"

CSPELL_COLOR="${WHITE}${BOLD}\e[40m"
CVERSION_COLOR="${WHITE}${BOLD}\e[40m"
CQUERY_COLOR="${YELLOW}${BOLD}"
CDISPEL_COLOR="${YELLOW}${BOLD}"
CCHECK_COLOR="${CYAN}"
CRESURRECT_COLOR="${GREEN}${BOLD}"
CFILE_COLOR="${GREEN}${BOLD}"
CSYMLINK_COLOR="${CYAN}${BOLD}"
CPROBLEM_COLOR="${RED}${BOLD}"
CMESSAGE_COLOR="${CYAN}"

#-------------------------------------------------------------------------------
# ERROR definitions
#-------------------------------------------------------------------------------
# cauldron errors
CERR_OK=0
CERR_ARCHIVE=1
CERR_CHROOT=2
CERR_CLEANFILE=3

# enchant errors
EERR_OK=0
EERR_STEP=1

#-------------------------------------------------------------------------------
# Function definitions
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
## @param type
##
## Checks for an error condition (via $?), and if found it will return an error
## of the specified type (arg1).
##
#-------------------------------------------------------------------------------
function cauldron_checkerror() {
  local type=$1
  local error=

  if [[ $? -gt 0 ]]
  then
    error=$type
  else
    error="${${type:0:1}ERR_OK}"
  fi
  return $error
}

function cauldron_printerror() {
  local error=$1
  local errmsg=

  echo "$CERR_COLOR" "$errmsg" "$CDEFAULT_COLOR"
}

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab

