#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  Global variable delinter - tests all global variables (as defined in the
##  API specification) for whether they are defined in a given definitions file.
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

DELINT_PATH="$(dirname $0)"

# load liberror (this is not optional)
if ! . "${CAULDRON_LIBS:-$DELINT_PATH/../lib}/liberror"
then
  echo "error: could not load ${CAULDRON_LIBS:-$DELINT_PATH/../lib}/liberror"
  exit 1
fi

# load libcolor (there should be an option for this later)
if ! . "${CAULDRON_LIBS:-$DELINT_PATH/../lib}/libcolor"
then
  echo "error: could not load ${CAULDRON_LIBS:-$DELINT_PATH/../lib}/libcolor"
  exit 1
fi

function delint_print_usage() {
  cat << EndUsage
Usage: $(basename $0) definition_file file_to_check1 [file_to_check2 ...]

Checks whether global variables in FILE_TO_CHECK1 [FILE_TO_CHECK2 ...] were
defined in DEFINITION_FILE. For any global variables not so defined, they are
printed on stdout along with the file in which they were used.
EndUsage
}

function delint_usage() {
  delint_print_usage
  exit $ERR_FATAL
}

defines="$1"
shift

if [[ ! -f "$defines" ]]
then
  echo "error: definition file not found"
  liberror_die $ERR_FATAL
fi

if [[ $# -eq 0 ]]
then
  echo "$(delint_print_usage)"
  liberror_die $ERR_FATAL
fi

while [[ $# -gt 0 ]]
do
  file="$1"
  shift

  [[ -f "$file" ]] || continue

  # as per the API specification, all global variables are required to be
  # uppercase, and must begin with a letter, containing only letters,
  # underscores, and trailing numbers
  for search in $(grep -o '${\?[A-Z][A-Z_]*[0-9]*' "$file" | sort -u | sed 's/^\${\?//')
  do
    grep -q "$search=" "$defines" || echo "$file: $search"
  done
done

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
