#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  Function and variable definitions for the delinters.
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

# set LC_COLLATE to C so we don't get affected by the user's locale
# when grepping, sorting, etc.
export LC_COLLATE="C"

# ensure that DELINT_PATH has a value
[[ -z "$DELINT_PATH" ]] && DELINT_PATH="$(dirname $0)"

# load liberror (this is not optional)
if ! . "$DELINT_PATH/../lib/liberror"
then
  echo "error: could not load $DELINT_PATH/../lib/liberror"
  exit 1
fi

# load libcolor (there should be an option for this later)
if ! . "$DELINT_PATH/../lib/libcolor"
then
  echo "error: could not load $DELINT_PATH/../lib/libcolor"
  exit 1
fi

function delint_global_variables() {
  local defines=""
  local file=""

  # get the defines file, then drop it from the argument list
  defines="$1"
  shift

  # make sure the defines file exists, otherwise we can't check anything
  if [[ ! -f "$defines" ]]
  then
    echo "error: definition file not found"
    liberror_die $ERR_FATAL
  fi

  while [[ $# -gt 0 ]]
  do
    file="$1"
    shift

    [[ -f "$file" ]] || continue

    # as per the API specification, all global variables are required to be
    # uppercase, and must begin with a letter, containing only letters,
    # underscores, and trailing numbers
    for search in $(grep -o '${\?[A-Z][A-Z_]*[0-9]*' "$file" | sed 's/^\${\?//' | sort -u)
    do
      if ! grep -q "$search=" "$defines"
      then
        echo "$(libcolor_file $file): $(libcolor_warn $search)"
      fi
    done
  done
}

function delint_error_codes() {
  local errorcodes="$1"
  local codes=()
  local msgcode=""
  local count=""

  # make sure the defines file exists, otherwise we can't check anything
  if [[ ! -f "$errorcodes" ]]
  then
    libcolor_error "error: error code file \"$errorcodes\" not found"
    echo ""
    liberror_die $ERR_FATAL
  fi

  if ! source "$errorcodes" 2 > /dev/null
  then
    libcolor_error "error: could not source error code file \"$errorcodes\""
    echo ""
  fi

  # get the list of defined error codes
  codes=( $(grep -o '^ERR_[A-Z_]\+[0-9]*' "$errorcodes" | grep -v 'ERR_MSGS') )

  # test if the number of messages matches the number of error codes
  if [[ "${#codes[@]}" -ne "${#ERR_MSGS[@]}" ]]
  then
    libcolor_error "error: number of error codes not equal to "
    libcolor_error "number of messages in \"$errorcodes\""
    echo ""
    libcolor_error "     codes: ${#codes[@]}"
    echo ""
    libcolor_error "  messages: ${#ERR_MSGS[@]}"
    echo ""

    echo "${codes[@]}"
  fi

  # for every error code defined, make sure there is a corresponding message
  for ((count=0; "$count" < "${#codes[@]}"; count++))
  do
    if ! grep -q "${codes[count]}\$" "$errorcodes"
    then
      libcolor_error "error: ${codes[count]} defined but has no corresponding message"
      echo ""
    fi
  done

  # for every error message defined, make sure there is a corresponding code
  for ((count=0; "$count" < "${#ERR_MSGS[@]}"; count++))
  do
    msgcode=$(grep "${ERR_MSGS[count]}.*# " "$errorcodes" | sed 's/.*# //')

    if ! grep -q "^${msgcode}=" "$errorcodes"
    then
      libcolor_error "error: $msgcode not defined but message is"
      echo ""
    fi
  done
}

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
