SMGL-Release-0.9.3-i386 done by Benoit PAPILLAULT 0e<benoit.papillault@sourcemage.org>07
and Laurent WANDREBECK 0e<lwandrebeck@sourcemage.org>07

09Welcome07 to 04Source Mage GNU/Linux07 (Linux kernel 2.6.8.1)
Copyright (C) 2000-2001 by Kyle Sallee
Copyright (C) 2002-2003 by Source Magers <www.sourcemage.org>
All Rights Reserved

Source Mage is distributed under the terms of the GNU General Public License
Version 2 Please see 01http://www.gnu.org/copyleft/gpl.html07 for the GNU GPL

Download Source Mage GNU/Linux and documentation from
01http://www.sourcemage.org07

* To install Source Mage GNU/Linux right now, just press 02enter07. If
  you need special kernel parameters, just type 02install07 followed by
  kernel parameters, like "acpi=off" for instance.

* To use this CD as a rescue CD, either type 02linux07 (or 02initrd07 to
  use the initrd to load kernel modules, needed for SCSI devices for
  instance) followed by usual kernel parameters, like 02root=07 to
  specify a root device.

