SMGL-Release-0.9.3-ppc (2004/10/05)

ISO done by Javier Lopez <de_Moya@sourcemage.org> and Benoit
PAPILLAULT <benoit.papillault@sourcemage.org>

Welcome to Source Mage GNU/Linux (Linux kernel 2.6.8.1)
Copyright (C) 2000-2001 by Kyle Sallee
Copyright (C) 2002-2004 by Source Magers <www.sourcemage.org>
All Rights Reserved
Source Mage is distributed under the terms of the GNU General Public License
Version 2 Please see http://www.gnu.org/copyleft/gpl.html for the GNU GPL

Download Source Mage GNU Linux and documentation from
http://www.sourcemage.org

* To install Source Mage GNU/Linux right now, just press 'enter'. If
  you need special kernel parameters, just type 'install' followed by
  kernel parameters, like "acpi=off" for instance.

* To use this CD as a rescue CD, either type 'linux' (or 'initrd' to
  use the initrd to load kernel modules, needed for SCSI devices for
  instance) followed by usual kernel parameters, like 'root=' to
  specify a root device.

