#!/bin/bash

# This file is the SMGL installer, at least for now.
# Take care not to pollute the user's namespace too much,
# And make sure your functions don't collide with existing commands

INSTALLER_TMP=/tmp/smgl.install
INSTALLER_STATUS=$INSTALLER_TMP/status
INSTALLER_DATA=/usr/share/smgl.install
INSTALLER_DOCS=/usr/share/doc/smgl.install

# This will race on startup, but it shouldn't harm anyone. I hope.
mkdir -p $INSTALLER_TMP
[[ -e $INSTALLER_STATUS ]] || echo 'init' >$INSTALLER_STATUS

function todo() {
  local CURSTEP
  CURSTEP=$(cat $INSTALLER_STATUS)
  cat $INSTALLER_DOCS/steps/$CURSTEP
}

function next() {
  local CURSTEP
  # get old status
  CURSTEP=$(cat $INSTALLER_STATUS)
  # find next status
  CURSTEP=$(grep "^$CURSTEP:" $INSTALLER_DATA/order | cut -d: -f2)
  # if we couldn't find a next status, jump to 'error'
  CURSTEP=${CURSTEP:-error}
  # save new status
  echo "$CURSTEP" >$INSTALLER_STATUS
  # print new message
  todo
}

function back() {
  local CURSTEP
  CURSTEP=$(cat $INSTALLER_STATUS)
  if [[ $CURSTEP != "init" ]] ;then
    CURSTEP=$(grep ":$CURSTEP$" $INSTALLER_DATA/order | head -n 1 | cut -d: -f1)
  fi
  CURSTEP=${CURSTEP:-error}
  echo "$CURSTEP" >$INSTALLER_STATUS
  todo
}

function list-steps() {
  cat $INSTALLER_DATA/steps
}

function jump() {
  echo "$*" >$INSTALLER_STATUS
}
