#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  These are the enchantment-specific error definitions.
##
##=head1 COPYRIGHT
##
##  Copyright 2009 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# ERROR definitions
#-------------------------------------------------------------------------------
# base error codes
liberror_add_error ERR_MK_DIR "could not make directory"
liberror_add_error ERR_DIR_EXISTS "directory already exists"
liberror_add_error ERR_FILE_ACCESS "file not accessible"
liberror_add_error ERR_DIR_ACCESS "directory not accessible"
liberror_add_error ERR_TARGET "invalid target parameter"

# libenchantment base
liberror_add_error ERR_LOAD_LIBRARY "could not load enchantment library"
liberror_add_error ERR_PREPARE "could not initialize enchantment"
liberror_add_error ERR_CLEANUP "could not clean up after finishing"
liberror_add_error ERR_VARIABLE "variable not found"

# libenchantment module processing
liberror_add_error ERR_GET_CURRENT "could not get current module"
liberror_add_error ERR_GET_NEXT "could not get next module"
liberror_add_error ERR_GET_PREV "could not get previous module"
liberror_add_error ERR_SET_CURRENT "could not set current module"
liberror_add_error ERR_SET_NEXT "could not set next module"
liberror_add_error ERR_SET_PREV "could not set previous module"

# lib.chroot
liberror_add_error ERR_CHROOT_INVALID "chroot target is undefined or invalid"
liberror_add_error ERR_CHROOT_ISROOT "chroot target equals the host root fs"
liberror_add_error ERR_CHROOT_INIT "could not initialize chroot"
liberror_add_error ERR_CHROOT_NOT_INIT "chroot not initialized"
liberror_add_error ERR_CHROOT_UNDEF "chroot command undefined"
liberror_add_error ERR_CHROOT_CURRENT "chroot not current or not defined"
liberror_add_error ERR_CHROOT_DONE "could not properly clean up chroot"
liberror_add_error ERR_CHROOT_EXEC "could not execute chroot command"

# lib.i18n keymap
liberror_add_error ERR_KEYMAP_EXIT "keymap processing finished"
liberror_add_error ERR_KEYMAP_PREFIX "invalid keymap prefix"
liberror_add_error ERR_KEYMAP_LIST "keymap list empty or not provided"
liberror_add_error ERR_KEYMAP_LIST_SIZE "invalid list size provided"
liberror_add_error ERR_KEYMAP_INPUT "invalid user input"
liberror_add_error ERR_KEYMAP_LOAD "could not load selected keymap"
liberror_add_error ERR_KEYMAP_GET "could not get selected keymap"
liberror_add_error ERR_KEYMAP_SET "could not set selected keymap"

# lib.install
liberror_add_error ERR_INSTALL_DIR "could not install directory"
liberror_add_error ERR_INSTALL_FILE "could not install file"
liberror_add_error ERR_INSTALL_CACHES "could not install spell caches"
liberror_add_error ERR_INSTALL_SOURCES "could not install spell sources"
liberror_add_error ERR_INSTALL_KERNEL "could not install kernel image"
liberror_add_error ERR_INSTALL_KMODS "could not install kernel modules"
liberror_add_error ERR_INSTALL_DEPMOD "could not perform depmod in install"

# lib.module
liberror_add_error ERR_MODULE_NONE "no modules found"
liberror_add_error ERR_MODULE_SCRIPT "could not process module script"
liberror_add_error ERR_MODULE_ENTER "could not process module entry"
liberror_add_error ERR_MODULE_EXIT "could not process module exit"
liberror_add_error ERR_MODULE_GET_NUM "could not get number of current module"

# history
liberror_add_error ERR_HISTORY_BACK "could not go back in install history"
liberror_add_error ERR_HISTORY_FORWARD "could not go forward in install history"

# lib.potion
liberror_add_error ERR_POTION_DIR "potion directory not found"
liberror_add_error ERR_POTION_GET_HASHSUM "could not read hashsum of file"
liberror_add_error ERR_POTION_SET_HASHSUM "could not store hashsum of file"
liberror_add_error ERR_POTION_CACHE_FILE \
  "could not copy file into potion directory"
liberror_add_error ERR_POTION_ARCHIVE_FORMAT "unknown archive format"
liberror_add_error ERR_POTION_ARCHIVE "could not make potion archive"
liberror_add_error ERR_POTION_COMPRESS "could not compress potion archive"

# lib.potion gets
liberror_add_error ERR_POTION_GET_BOOTLOADER "could not read bootloader config"
liberror_add_error ERR_POTION_GET_CONFS "could not read target system configs"
liberror_add_error ERR_POTION_GET_FILESYSTEMS "could not read filesystems"
liberror_add_error ERR_POTION_GET_KERNEL "could not read kernel config"
liberror_add_error ERR_POTION_GET_MOUNT_POINTS "could not read mount points"
liberror_add_error ERR_POTION_GET_OPT_SPELLS \
  "could not read optional spell selection"
liberror_add_error ERR_POTION_GET_PARTITIONS "could not read partitions"
liberror_add_error ERR_POTION_GET_USERS "could not read user/group config"

# lib.potion updates
liberror_add_error ERR_POTION_UPDATE_BOOTLOADER \
  "could not update bootloader config"
liberror_add_error ERR_POTION_UPDATE_CONFS \
  "could not update target system configs"
liberror_add_error ERR_POTION_UPDATE_FILESYSTEMS "could not update filesystems"
liberror_add_error ERR_POTION_UPDATE_KERNEL "could not update kernel config"
liberror_add_error ERR_POTION_UPDATE_MOUNT_POINTS \
  "could not update mount points"
liberror_add_error ERR_POTION_UPDATE_SOURCES \
  "could not update spell sources selection"
liberror_add_error ERR_POTION_UPDATE_CACHES \
  "could not update spell caches selection"
liberror_add_error ERR_POTION_UPDATE_PARTITIONS "could not update partitions"
liberror_add_error ERR_POTION_UPDATE_USERS "could not update user/group config"

# installer
liberror_add_error ERR_INSTALLER_FUNCS \
  "could not load \$ENCHANT_INSTALLER functions file"
liberror_add_error ERR_INSTALLER_CMD "incorrect usage or unrecognized command"
liberror_add_error ERR_INSTALLER_KEYMAP "could not process keymap list"
liberror_add_error ERR_INSTALLER_MODULES "could not process module list"

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
