#!/bin/bash
SCRIPTDIR=${0%/*}
if [[ "${SCRIPTDIR:0:1}" != "/" ]] ;then
  SCRIPTDIR=$(pwd)/$SCRIPTDIR # turn into absolute path
fi
# all paths should be absolute
CACHE_DIR=/var/cache/sorcery
STATE_DIR=$SCRIPTDIR/../data
SKELETON=$SCRIPTDIR/../skeleton

ISO_BRANCH=${ISO_BRANCH:-stable}
ARCH=${ARCH:-i486-pc-linux-gnu}
ISO_ARCH=${ISO_ARCH:-x86}
  # generic i386 and family
SVERSION=${SVERSION:-stable}
GVERSION=${GVERSION:-stable}
KVERSION=${KVERSION:-"2.6"}
KERNEL_VERSION=${KERNEL_VERSION:-2.6.14.2}
if [[ $KERNEL_VERSION == *.*.*.* ]] ;then
  KERNEL_MVERSION=${KERNEL_MVERSION:-${KERNEL_VERSION%.*}}
  KERNEL_PATCHES=${KERNEL_PATCHES:-"patch-$KERNEL_VERSION"}
else
  KERNEL_MVERSION=${KERNEL_MVERSION:-$KERNEL_VERSION}
  # leave KERNEL_PATCHES unset if unset, otherwise don't change.
fi
ISO_VERSION=0.9.6
ISO_FILENAME="smgl-${ISO_VERSION}-$ISO_ARCH.iso"
IGNORE_FATAL=${IGNORE_FATAL:-no}

INITRDROOT=${INITRDROOT:-/theinitrd}
ISO_DIR=${ISO_DIR:-/iso-root} # kept around for easy debugging

ISO_STATE_DIR=$ISO_DIR/var/lib/smgl.install
. $SCRIPTDIR/misc
