#!/bin/bash

[ -e /etc/smgl-isogen.conf ] && . /etc/smgl-isogen.conf

SCRIPTDIR=${0%/*}
if [[ "${SCRIPTDIR:0:1}" != "/" ]] ;then
  SCRIPTDIR=$(pwd)/$SCRIPTDIR # turn into absolute path
fi
# all paths should be absolute
CACHE_DIR=/var/cache/sorcery
STATE_DIR=$SCRIPTDIR/../data
SKELETON=$SCRIPTDIR/../skeleton

ISO_BRANCH=${ISO_BRANCH:-devel}
# Don't worry, that echo runs in a subshell
ARCH=${ARCH:-$(. /etc/sorcery/config ; echo $HOST)}
ISO_ARCH=${ISO_ARCH:-$(uname -m)}
# FIXME: this is a brutal hack, but the best I could come up with
# on short notice...
[[ $ISO_ARCH == ppc ]] || [[ $ISO_ARCH == x86_64 ]] || ISO_ARCH=i486
SVERSION=${SVERSION:-test}
GVERSION=${GVERSION:-test}
KVERSION=${KVERSION:-"2.6"}

# "local" helper variables
kconf=../data/config-$KVERSION.$ISO_ARCH
[[ -e $kconf ]] || kconf=../data/config-$KVERSION
def_kv=$(sed -n 's/^# Linux kernel version: //p' $kconf)

KERNEL_VERSION=${KERNEL_VERSION:-$def_kv}
if [[ $KERNEL_VERSION == *.*.*.* ]] ;then
  KERNEL_MVERSION=${KERNEL_MVERSION:-${KERNEL_VERSION%.*}}
  KERNEL_PATCHES=${KERNEL_PATCHES:-"patch-$KERNEL_VERSION"}
else
  KERNEL_MVERSION=${KERNEL_MVERSION:-$KERNEL_VERSION}
  # leave KERNEL_PATCHES unset if unset, otherwise don't change.
fi
ISO_VERSION=${ISO_VERSION:-$ISO_BRANCH-$(cat $STATE_DIR/internal_version)}
ISO_FILENAME="smgl-${ISO_VERSION%%-*}-$ISO_ARCH-$KERNEL_VERSION-nptl-${ISO_VERSION#*-}.iso"
IGNORE_FATAL=${IGNORE_FATAL:-yes}

INITRDROOT=${INITRDROOT:-/theinitrd}
ISO_DIR=${ISO_DIR:-/iso-root} # kept around for easy debugging

ISO_STATE_DIR=$ISO_DIR/var/lib/smgl.install
. $SCRIPTDIR/misc
