#!/bin/bash
# This script attempts to automatically build all tarballs we need for the ISO

# First, grab configuration, fwiw
. ${0%/*}/config

# Generate lists of spells we need tarballs of,
# and of spells that shouldn't get dispelled
${0%/*}/listparse

# First cast all critical spells (for the sake of paranoia),
# then create all tarballs we need
${0%/*}/caster -c $( cat $STATE_DIR/list.reqd $STATE_DIR/list.all )
