#!/bin/bash
# This is a little wrapper script to generate an ISO from inside a chroot
# with existing tarballs.

# Grab config
. ${0%/*}/config

# Cast all spells we said we'd need
echo "checking for spells required for the generation process..."
while read -u 3 spell ; do
  gaze installed $spell || cast $spell
done 3<$STATE_DIR/smgl.genspells

# Make initrd image
./mkinitrd
# Make iso image
./mkiso
