#!/bin/bash
SCRIPTDIR=${0%/*}
. $SCRIPTDIR/config
CHROOTGEN=$SCRIPTDIR/../../chroot

if [[ -z $2 ]] ;then
  echo "Syntax: $0 <path to root to generate from> <path to put new root>"
  exit 2
fi

cp $CHROOTGEN/chrootgen.sh $1/
rm -r $1/chroot-configset $1/new-root $1/tmp/backup_configs
cp -a $CHROOTGEN/$ISO_ARCH $1/chroot-configset

#FIXME: Force specific grimoire to be updated and used (preferrably without
# leaving a lasting trace (e.g. grimoire update) on the host)

chroot $1 /chrootgen.sh --chroot_dir /new-root --config_dir /chroot-configset \
  --backup_dir /tmp/backup_configs recreate

pushd $1/new-root
mkdir -p proc dev sys tmp var/spool/sorcery
cd dev
$1/var/lib/sorcery/codex/*/smgl/init.d/MAKEDEV generic

popd
mkdir -p $2
rmdir $2 &&
mv $1/new-root $2
