#!/bin/bash
# file for architecture optimizations

function arch_screen() {

  want_dependency disk          &&
  want_dependency install_start ||
  return 1

  if confirm "do you want to configure make jobs and distcc? (advanced)" \
       --defaultno ;then
    export CONFIG_DISTCC=yes
  fi

  (
    exit() {
      true
    }
    . /usr/sbin/sorcery -v >/dev/null
    optimize_architecture
    [[ $CONFIG_DISTCC ]] && parallel_compilation_menu
  )

  unset CONFIG_DISTCC
  cp --parents -a /etc/sorcery/local/config $FINALFILES
  cp --parents -a /etc/sorcery/local/compile_config $FINALFILES

}
