#!/bin/bash
# this is the module for native language support

#native language support screen
nls_screen()  {

  local FONT_HELP KEYMAP_HELP LANG_HELP EDITOR_HELP

  local COMMAND

  mkdir -p ${FINALFILES}/etc/profile.d
  fill_dependency keymap defkeymap #So it's picked up right in the help line

  while

      FONT_HELP="Select a new default console font."
    KEYMAP_HELP="Select a new default keyboard mapping. (is $(get_dependency keymap))"
      LANG_HELP="Select a new default language. (currently is $LANG)"
    EDITOR_HELP="Select a new default editor."
    COMMAND=`run_dialog  --cancel-label  "Continue"                 \
             --ok-label "Select"                                    \
             --title  "Native Language Support Menu"                \
             --item-help                                            \
             --menu "Select options to customize your SMGL install" \
             7 60 0                                                 \
             "Font"    "Font     Menu "  "$FONT_HELP"               \
             "Keymap"  "Keymap   Menu "  "$KEYMAP_HELP"             \
             "Lang"    "Language Menu "  "$LANG_HELP"               \
             "Editor"  "Editor   Menu "  "$EDITOR_HELP"`
  do
    case  $COMMAND in
        Keymap)  keymap_menu  ;;
          Font)  font_menu    ;;
          Lang)  lang_menu    ;;
        Editor)  editor_menu  ;;
    esac
  done

  return 0
}

keymap_menu()  {

  local KEYMAP
  declare -a KEYMAPS
  get_keymaps                                                 &&

  KEYMAP=`run_dialog                                          \
          --title "Keymap Selection Menu"                     \
          --menu  "Please select your preferred keymapping."  \
          7 60 0                                              \
          "${KEYMAPS[@]}"`                                    &&

  unset KEYMAPS                                               &&

  debug_log "NLS" 1 "Chose keymapping $KEYMAP"                  &&
  loadkeys  $KEYMAP                                           &&
  fill_dependency keymap $KEYMAP                              &&
  sed -i "s/^KEYMAP=.*$/KEYMAP=$KEYMAP/" ${FINALFILES}/etc/sysconfig/keymap

}

font_menu()  {

  local FONT
  declare -a FONTS
  get_consolefonts                                             &&

  FONT=`run_dialog                                             \
        --title  "Console Font Selection Menu"                 \
        --menu   "Please select your preferred console fonts." \
        7 60 0                                                 \
        "${FONTS[@]}"`                                         &&

  debug_log "NLS" 1 "Chose console font $FONT"                   &&

  consolechars  -f  $FONT

  sed -i "s/^CONSOLECHARS_ARGS=.*$/CONSOLECHARS_ARGS=\"-f $FONT\"/" \
    ${FINALFILES}/etc/sysconfig/keymap                         &&

  unset FONTS
}

lang_menu()  {

  local HELP="While sorcery is entirely in English it is possible to
change the languages of many other programs.  Please
select your preferred language."

  declare -a LANGS
  get_languages                        &&

  LANG=`run_dialog                     \
        --trim --title "Language Selection Menu" \
        --menu   "$HELP"               \
        9 60 0                         \
        "${LANGS[@]}"`                 &&
  export LANG                          &&

  run_template $TEMPLATE_DIR/lc.sh $TEMPLATE_DIR/nls.patterns \
    >${FINALFILES}/etc/profile.d/lc.sh &&
  unset LANGS                          &&

  debug_log "NLS" 1 "Chose LANG=$LANG"
}

editor_menu()  {

  local ELVIS_DSC="elvis is a clone of the ex/vi text editor"
  local   JED_DSC="jed is an editor with emulation for emacs, EDT, and Wordstar"
  local  NANO_DSC="nano is an enchanced free pico clone"
  local   VIM_DSC="VIM is an improved version of vi"
  local REAL_ED

  local HELP="The Install/Rescue disc provides two easy to use
editors, elvis and nano. Four common editors can be
installed, although selecting vim will still use
elvis during the install"

  REAL_ED=`run_dialog --title  "Editor Selection Menu" \
           --item-help --single-quoted                 \
           --default-item "${EDITOR}"                  \
           --radiolist   "$HELP" 10 60 0               \
           "nano"  "a pico clone"  "off"  "$NANO_DSC"  \
           "jed" "Powerful editor" "off"   "$JED_DSC"  \
           "elvis" "A vi clone"    "off" "$ELVIS_DSC"  \
           "vim"   "VI IMproved"   "off"   "$VIM_DSC"` &&

  # REAL_ED is the editor that will be installed on the new system
  # EDITOR is the editor used throughout the install process
  # since vim/elvis conflicts, only elvis is installed (smaller)

  if [ "${REAL_ED}" = "vim" ]; then
    export EDITOR="elvis"
  else
    export EDITOR=$REAL_ED
  fi                                                   &&

  debug_log "NLS" 1 "chose $REAL_ED as EDITOR"            &&

  si_queue $REAL_ED                                    &&

  run_template $TEMPLATE_DIR/editor.sh $TEMPLATE_DIR/nls.patterns \
    >${FINALFILES}/etc/profile.d/editor.sh
}

get_keymaps()  {

  local idx=0
  local line
  while read line ; do
    KEYMAPS[idx++]=$line
  done <$STATE_DIR/keyMapList

}

get_consolefonts()  {

  local idx=0
  local line
  while read line ; do
    FONTS[idx++]=$line
  done <$STATE_DIR/fontList

}

get_languages()  {

  local idx=0
  local line
  while read line ; do
    LANGS[idx++]=$line
  done <$STATE_DIR/languageList

}
