#!/bin/bash

#module for syslog stuff
function logger_screen() {
  need_dependency disk          &&
  need_dependency install_start &&
  syslog
}

syslog()  {

  local logger
  logger=$(memory_menu logger "Please select your system logger"       \
            "--item-help" "Pick one of the 3 loggers available" "none" \
            "sysklogd"  "standard system logging daemon"               \
"This version of syslogd is similar to the standard Berkeley product." \
            "syslog-ng" "new logging daemon with some more features"   \
            "syslog-ng, as the name shows, is a syslogd replacement."  \
            "metalog"   "a modern replacement for the loggers"         \
           "metalog has many features and allows high configurability" \
            "none"      "no logger"                                    \
            "don't want/need a system logger")                        &&
  debug_log "syslog" 1 "Chose \"$logger\" as system logger"           &&
  fill_dependency syslog $logger                                      &&
  if [[ $logger == "none" ]] ;then return 0 ;fi                       &&
  si_queue $logger                                                    &&
  try_run sed -i "s/^syslog=.*$/syslog=$(slg_get_initscript_name $logger)/" \
    ${FINALFILES}/etc/sysconfig/facilities
}

function slg_get_initscript_name() {
  case "$1" in
    "sysklogd") echo "sysklogd"     ;;
   "syslog-ng") echo "syslog-ng"    ;;
     "metalog") echo "smgl-metalog" ;;
  esac
}
