#!/bin/bash

function usage() {
  cat <<USAGE
Usage: $(basename $0) [-h] [-d /path/to/target]

Installs the ISO kernel and it's modules to the target specified. If no target
is specified on the command-line, it installs to /mnt/root by default.

Options:
	-h  Shows this help information
USAGE
  exit 1
} >&2

while getopts ":h" Option
do
  case $Option in
    h ) usage ;;
    * ) echo "Unrecognized option." >&2 && usage ;;
  esac
done
shift $(($OPTIND - 1))

[[ $# -eq 1 ]] && TARGET="$1"
TARGET="${TARGET:-/mnt/root}"

# Copy the kernel config
echo "Installing kernel config to $TARGET/boot/config-$(uname -r)"
cp -f /boot/config-$(uname -r) "$TARGET"/boot/config-$(uname -r)

# Copy the kernel image
echo "Installing kernel to $TARGET/boot/vmlinuz-$(uname -r)"
cp -f /boot/linux "$TARGET"/boot/vmlinuz-$(uname -r)
while true
do
  echo -n "Create /boot/vmlinuz symlink? [yn] "
  read -n1 input
  echo ""
  case $input in
    "y" ) ln -sf "$TARGET"/boot/vmlinuz-$(uname -r) "$TARGET"/boot/vmlinuz
          break
          ;;
    "n" ) break
          ;;
  esac
done

# Copy all kernel modules
[[ -d "$TARGET"/lib/modules ]] || mkdir -p "$TARGET"/lib/modules
echo "Installing kernel modules to $TARGET/lib/modules/$(uname -r)"
cp -fr /lib/modules/$(uname -r) "$TARGET"/lib/modules/

[[ ! -d "$TARGET"/etc/modprobe.d ]] && mkdir -p "$TARGET"/etc/modrobe.d
echo "Installing modprobe blacklist to $TARGET/etc/modprobe.d/blacklist"
cp -f /etc/modprobe.d/blacklist "$TARGET"/etc/modprobe.d/blacklist


# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:ai
