#!/bin/bash

function usage() {
  cat <<USAGE
Usage: $(basename $0) [-h] [-d /path/to/target]

Installs the ISO kernel and it's modules to the target specified. If no target
is specified on the command-line, it installs to /mnt/root by default.

Options:
	-h  Shows this help information
USAGE
  exit 1
} >&2

while getopts ":h" Option
do
  case $Option in
    h ) usage ;;
    * ) echo "Unrecognized option." >&2 && usage ;;
  esac
done
shift $(($OPTIND - 1))

[[ $# -eq 1 ]] && TARGET="$1"
TARGET="${TARGET:-/mnt/root}"

# Copy the kernel config
cp -f /boot/config-$(uname -r) "$TARGET"/boot/config-$(uname -r)-SMGL-iso

# Copy the kernel image
cp -f /boot/linux-$(uname -r) "$TARGET"/boot/vmlinuz-$(uname -r)-SMGL-iso

# Copy all kernel modules
[[ -d "$TARGET"/lib/modules ]] || mkdir -p "$TARGET"/lib/modules
cp -fr /lib/modules/$(uname -r) "$TARGET"/lib/modules/


# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:ai
