#!/bin/bash

# Check if called with optional argument,
# If yes then R00T=$1, else ROOT=/mnt/root
ROOT="${1:-/mnt/root}"

# Note: don't use --rbind: It creates several mounts, and we wouldn't be able
# to figure out easily what to umount.
mount --bind /dev "$ROOT"/dev         &&
mount --bind /dev/pts "$ROOT"/dev/pts &&
mount --bind /proc "$ROOT"/proc       &&

# set the prompt for inside the chroot to reflect the fact that the user is chrooted
export PS1="[inside chroot, type [1mexit[m to return to installer]\n\u \w\$ " &&

chroot "$ROOT" "$@"

# clean up the chroot mounts
umount "$ROOT"/proc
umount "$ROOT"/dev/pts
umount "$ROOT"/dev


# vim:sw=2:ts=2:softtabstop=2:expandtab:ai
