#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  This file is the SMGL shell installer.
##  Take care not to pollute the user's namespace too much,
##  And make sure your functions don't collide with existing commands.
##
##=head1 COPYRIGHT
##
##  Copyright 2009 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

. "/etc/cauldron/enchant.config"
. "/etc/cauldron/local/enchant.config" 2> /dev/null
. "${ENCHANT_DATA}/libenchantment"

if enchant_color
then
  . "${ENCHANT_BASE}/libcolor" ||
    liberror_print_error $ERR_LIBCOLOR $LIBERR_STDERR
fi

# Ensure installer sanity
enchant_prepare

function header() {
  local doc
  doc=$1
  echo ""
  echo ""
  echo ""
  cat $1
}

function todo() {
  local CURSTEP=$(enchant_getstep)

  header ${ENCHANT_MSGS}/steps/$CURSTEP
}

function next_step() {
  enchant_getnext
}

function cur_step() {
  enchant_getstep
}

function next() {
  enchant_setnext
  todo
}

function prev() {
  enchant_setprev
  todo
}

function num_current() {
  enchant_getnum
}

function num_steps() {
  enchant_gettotal
}

function steps() {
  header $ENCHANT_DATA/shell/steps
}

function back() {
  enchant_back
}

function forward() {
  enchant_forward
}

function jump() {
  enchant_setstep $*
  if [[ $? = $ERR_STEP ]]
  then
    echo ""
    echo "Error: '$*' is not a recognized step."
    echo "Type [1msteps[m to see a list of steps."
  fi
}

function welcome() {
  header ${ENCHANT_MSGS}/welcome
}

function help() {
  helpfile=${ENCHANT_MSGS}/help/${1:-index}
  if [[ -e $helpfile ]] ;then
    header $helpfile
  else
    echo "No installer help for '$1', falling back to bash's builtin help"
    builtin help $1
  fi
}

PS1="[current:\$(cur_step) next:\$(next_step) \$(num_current)/\$(num_steps)] For a list of commands, type [1mhelp[m\n\u \w\$ "

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
