#!/bin/bash
# all paths should be absolute
SYSROOT=/
CACHE_DIR=/var/cache/sorcery
KERNEL_VERSION=$(uname -r)
STATE_DIR=$(pwd)/../../data/bearscripts
SKELETON=$(pwd)/../../skeleton

ARCH=i686-pc-linux-gnu
ISO_ARCH=i686
ISO_VERSION=devel
IGNORE_FATAL=yes

INITRDROOT=$(pwd)/theinitrd # will be deleted
ISO_DIR=$(pwd)/iso-root # not deleted yet for debugging, will be soon.

output_warning()
{
  echo $1 1>&2
}

fatal_warning()
{
  echo $1 1>&2
  [ "$IGNORE_FATAL" == "yes" ] ||
  exit 1;
}
