#!/bin/bash
# Check_modules
# PCMCIA and net modules
# Markku (Rasatmakananda)<rasat@pacific.net.sg
# 2-May-2003

PATH="/bin:/usr/bin:/sbin:/usr/sbin"; export PATH
umask 022

# [ "`id -u`" != "0" ] && echo "WARNING: $0 has to run as root to work properly." 1>&2

# ANSI COLORS
CRE="
[K"
NORMAL="[0;39m"
# RED: Failure or error message
RED="[1;31m"
# GREEN: Success message
GREEN="[1;32m"
# YELLOW: Descriptions
YELLOW="[1;33m"
# BLUE: System messages
BLUE="[1;34m"
# MAGENTA: Found devices or drivers
MAGENTA="[1;35m"
# CYAN: Questions
CYAN="[1;36m"
# BOLD WHITE: Hint
WHITE="[1;37m"

md="/proc/modules"
list="/etc/hwd/device_list"

# PCMCIA modules
echo -n "${GREEN}PCMCIA Card  : ${NORMAL}"

cp /var/lib/pcmcia/dummy /var/lib/pcmcia/dummy.tmp
cp /var/lib/pci/dummy /var/lib/pci/dummy.tmp

if grep -q 3c589_cs $md; then
echo "3Com 3c589 PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe 3c589_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q 3c574_cs $md; then
echo "3Com 3c574 PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe 3c574_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q fmvj18x_cs $md; then
echo "Fujitsu FMV-J18x PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe fmvj18x_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q pcnet_cs $md; then
echo "NE2000 compatible PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe pcnet_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q axnet_cs $md; then
echo "Asix AX88190 PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe axnet_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q nmclan_cs $md; then
echo "New Media PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe nmclan_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q smc91c92_cs $md; then
echo "SMC 91Cxx PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe smc91c92_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q xirc2ps_cs $md; then
echo "Xircom 16-bit PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe xirc2ps_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q com20020_cs $md; then
echo "COM20020 ARCnet PCMCIA Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe com20020_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q ibmtr_cs $md; then
echo "IBM PCMCIA Token Ring Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe ibmtr_cs.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q xircom_tulip_cb $md; then
echo "Xircom Tulip-like CardBus"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe xircom_tulip_cb.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if grep -q xircom_cb $md; then
echo "Xircom CardBus"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe xircom_cb.o"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
rm /var/lib/pcmcia/dummy.tmp
fi

if [  -f /var/lib/pcmcia/stab ]; then
st="/var/lib/pcmcia/stab"
else
st="/var/lib/pcmcia/dummy"
fi

if grep -q ide-cs $st; then
echo "Compacflash Card"
echo " ${GREEN}Load PCMCIA module: ${NORMAL}modprobe pcmcia_core, i82365, ds, ide-cs"
echo " ${GREEN}Start network run : ${NORMAL}cardmgr -f"
echo " ${GREEN}        ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDP="yes"
fi

if [ -n "$FOUNDP" ]; then
dummy=""
else
echo "${RED}No PCMCIA card found.${NORMAL}"
fi

if [  -f /var/lib/pcmcia/dummy.tmp ]; then
if [  -f /var/lib/pcmcia/stab ]; then
echo "${NORMAL}Unknown PCMCIA card (/var/lib/pcmcia/stab):"
cat /var/lib/pcmcia/stab
fi
fi

if [  -f /var/lib/pcmcia/dummy.tmp ]; then
rm /var/lib/pcmcia/dummy.tmp
fi

# Ethernet modules
echo -n "${GREEN}Ethernet Card: ${NORMAL}"

if grep -q wd $md; then
echo "WD80*3 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe wd.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q smc-mca $md; then
echo "SMC Ultra MCA Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe smc-mca.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q smc-ultra $md; then
echo "SMC Ultra Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe smc-ultra.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q smc9194 $md; then
echo "SMC 9194 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe smc9194.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ne2k-pci $md; then
echo "PCI NE2000 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ne2k-pci.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ni5010 $md; then
echo "Racal-Interlan (Micom) NINI5010 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ni5010.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ni52 $md; then
echo "Racal-Interlan (Micom) NINI5210 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ni52.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ni65 $md; then
echo "Racal-Interlan (Micom) NI6510 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ni65.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 8139cp $md; then
echo "RealTek RTL-8139C+ 10/100 PCI Fast Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 8139cp.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 8139too $md; then
echo "RealTek RTL-8139 PCI Fast Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 8139too.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sis900 $md; then
echo "SiS 900/7016 PCI Fast Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sis900.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q yellowfin $md; then
echo "Packet Engines Yellowfin Gigabit-NIC / Symbios 53c885 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe yellowfin.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sb1000 $md; then
echo "General Instruments Surfboard 1000 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sb1000.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q starfire $md; then
echo "Adaptec Starfire & DuraLAN) PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe starfire.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q acenic $md; then
echo "Alteon AceNIC, 3Com 3C985(B), NetGear, GA620, SGI Gigabit (Farallon)"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe acenic.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sk98lin $md; then
echo "SysKonnect SK-98xx Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sk98lin.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sungem $md; then
echo "Sun GEM & Sun GigabitEthernet/P 2.0 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sungem.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q tg3 $md; then
echo "Broadcom Tigon3 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe tg3.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q myri_sbus $md; then
echo "MyriCOM Gigabit Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe myri_sbus.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q dl2k $md; then
echo "D-Link 2000-based Gigabit Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe dl2k.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q e100 $md; then
echo "EtherExpress Pro/100 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe e100.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q e1000 $md; then
echo "Intel(R) PRO/1000 Gigabit Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe e1000.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q lance $md; then
echo "AMD LANCE and PCnet (AT1500 and NE2100) Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe lance.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c501 $md; then
echo "3COM 3c501 'EtherLink'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c501.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c503 $md; then
echo "3COM 3c503 'EtherLink II'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c503.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c505 $md; then
echo "3COM 3c505 'EtherLink Plus'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c505.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c507 $md; then
echo "3COM 3c507 'EtherLink 16'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c507.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c523 $md; then
echo "3COM 3c523 'EtherLink/MC'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c523.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c527 $md; then
echo "3COM 3c527 'EtherLink/MC 32'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c527.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c509 $md; then
echo "3COM 3c509/3c529 (MCA)/3c579 'EtherLink III'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c509.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c515 $md; then
echo "3COM 3c515 ISA Fast EtherLink"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c515.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q 3c59x $md; then
echo "3COM 3c590/3c900 series (592/595/597) 'Vortex/Boomerang/Cyclone'"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe 3c59x.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q arcnet $md; then
echo "Generic ARCnet Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe arcnet.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q rfc1051 $md; then
echo "Enabled old ARCNet packet format (RFC 1051)"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe rfc1051.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q rfc1201 $md; then
echo "Enabled standard ARCNet packet format (RFC 1201)"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe rfc1201.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q arc-rawmode $md; then
echo "Enabled raw mode packet interface"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe arc-rawmode.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q com90xx $md; then
echo "ARCnet COM90xx (normal) Ethernet chipset"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe com90xx.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q com90io $md; then
echo "ARCnet COM90xx (IO mapped) Ethernet chipset"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe com90io.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q arc-rimi $md; then
echo "ARCnet COM90xx (RIM I) Ethernet chipset"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe arc-rimi.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q com20020 $md; then
echo "ARCnet COM20020  Ethernet chipset"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe com20020.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q e2100 $md; then
echo "Cabletron E21xx Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe e2100.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q cs89x $md; then
echo "Daynaport CS and LC Ethernet"
echo " ${GREEN}Load Ethernet module: ${NORMAL}modprobe cs89x.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q depca $md; then
echo "DEPCA, DE10x, DE200, DE201, DE202, DE422 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe depca.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ewrk3 $md; then
echo "EtherWORKS 3 (DE203, DE204, DE205) Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ewrk3.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q at1700 $md; then
echo "AT1700/1720 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe at1700.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q fmv18x $md; then
echo "FMV-181/182/183/184 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe fmv18x.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q eepro $md; then
echo "EtherExpressPro and EtherExpress 10 (i82595)"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe eepro.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q hamachi $md; then
echo "Packet Engines Hamachi GNIC-II Gigabit Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe hamachi.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q hp-plus $md; then
echo "HP PCLAN+ (27247B and 27252A) Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe hp-plus.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q hp $md; then
echo "HP PCLAN (27245 and other 27xxx series) Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe hp.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

## criteria "ne" is too narrow as grep search
# if grep -q ne $md; then
# echo "NE2000/NE1000 Ethernet"
# echo " ${GREEN}Load Ethernet module: ${NORMAL}modprobe ne.o"
# FOUNDE="yes"
# rm /var/lib/pci/dummy.tmp
# fi

if grep -q natsemi $md; then
echo "National Semiconductor DP8381x series PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe natsemi.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ne2 $md; then
echo "NE/2 (ne2000 MCA version) Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ne2.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sk_mca $md; then
echo "SKnet MCA - Micro Channel Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sk_mca.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ibmlana $md; then
echo "IBM LAN  Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ibmlana.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ac3200 $md; then
echo "Ansel Communications EISA 3200 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ac3200.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q lne390 $md; then
echo "Mylex EISA LNE390A/LNE390B Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe lne390.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ne3210 $md; then
echo "Novell/Eagle/Microdyne NE3210 EISA Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ne3210.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q de4x5 $md; then
echo "Generic DECchip & DIGITAL EtherWORKS PCI/EISA"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe de4x5.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q tulip $md; then
echo "DECchip Tulip (dc21x4x) PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe tulip.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q dgrs $md; then
echo "Digi Intl. RightSwitch SE-X Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe dgrs.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q eepro100 $md; then
echo "EtherExpress Pro/100"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe eepro100.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q fealnx $md; then
echo "Myson MTD-8xx PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe fealnx.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q lp486e $md; then
echo "LP486E on board Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe lp486e.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q eth16i $md; then
echo "ICL EtherTeam 16i/32"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe eth16i.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q tlan $md; then
echo "TI Thunder LAN Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe tlan.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q via-rhine $md; then
echo "VIA Rhine Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe via-rhine.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q dmfe $md; then
echo "Davicom DM910x/DM980x Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe dmfe.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q es3210 $md; then
echo "Racal-Interlan EISA ES3210 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe es3210.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q epic100 $md; then
echo "SMC EtherPower II Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe epic100.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sundance $md; then
echo "Sundance Alta PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sundance.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q atp $md; then
echo "AT-LAN-TEC/RealTek pocket Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe atp.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q de600 $md; then
echo "D-Link DE600 pocket Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe de600.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q de620 $md; then
echo "D-Link DE620 pocket Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe de620.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q ibmtr $md; then
echo "IBM Tropic Ethernet chipset"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe ibmtr.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q olympic $md; then
echo "IBM Olympic Ethernet chipset PCI"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe olympic.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q lanstreamer $md; then
echo "IBM Lanstreamer Ethernet chipset PCI"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe lanstreamer.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q tms380tr $md; then
echo "Generic TMS380 Token Ring ISA/PCI/MCA/EISA"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe tms380tr.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q tmspci $md; then
echo "Generic TMS380 PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe tmspci.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q tmsisa $md; then
echo "Generic TMS380 ISA Card"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe tmsisa.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q abyss $md; then
echo "Madge Smart 16/4 PCI Mk2"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe abyss.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q madgemc $md; then
echo "Madge Smart 16/4 Ringnode MicroChannel"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe madgemc.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q smctr $md; then
echo "SMC ISA/MCA Token Ring"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe smctr.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sunhme $md; then
echo "Sun Happy Meal 10/100baseT Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sunhme.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sunlance $md; then
echo "Sun Lance - NE2100 Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sunlance.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sunbmac $md; then
echo "Sun BigMAC 10/100baseT Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sunbmac.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q sunqe $md; then
echo "Sun Quad Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe sunqe.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q shaper $md; then
echo "Traffic Shaper Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe shaper.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q defxx $md; then
echo "Digital DEFEA and DEFPA Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe defxx.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q skfp $md; then
echo "SysKonnect FDDI PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe skfp.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if grep -q rrunner $md; then
echo "Essential RoadRunner HIPPI PCI Ethernet"
echo " ${GREEN}Load Ethernet module    : ${NORMAL}modprobe rrunner.o"
echo " ${GREEN}Start network add module: ${NORMAL}modprobe dummy"
echo " ${GREEN}              ...and run: ${NORMAL}dhcpcd eth0 (if dhcp is installed)"
FOUNDE="yes"
rm /var/lib/pci/dummy.tmp
fi

if [ -n "$FOUNDE" ]; then
dummy=""
else
echo "${RED}No Ethernet.${NORMAL} If you do have check 'Modules detected'"
fi

if [  -f /var/lib/pci/dummy.tmp ]; then
if [  -f /proc/pci ]; then
echo "${NORMAL}Unknown Ethernet card (/proc/pci):"
grep "Ethernet" /proc/pci
rm /var/lib/pci/dummy.tmp
fi
fi


