#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  libcolor defines various colors to be used and functions to manipulate them
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

# initialize for color - can be overridden after libcolor is loaded
LIBCOLOR_NOCOLOR="no"

#-------------------------------------------------------------------------------
# Message Color Definitions
#-------------------------------------------------------------------------------
LIBCOLOR_NORMAL="[0m"
LIBCOLOR_BOLD="[1m"
LIBCOLOR_BLACK="[30m"
LIBCOLOR_RED="[31m"
LIBCOLOR_GREEN="[32m"
LIBCOLOR_YELLOW="[33m"
LIBCOLOR_BLUE="[34m"
LIBCOLOR_VIOLET="[35m"
LIBCOLOR_CYAN="[36m"
LIBCOLOR_WHITE="[37m"

LIBCOLOR_NORMAL_COLOR="${LIBCOLOR_NORMAL}${LIBCOLOR_WHITE}"
LIBCOLOR_NOTICE_COLOR="${LIBCOLOR_BOLD}${LIBCOLOR_BLUE}"
LIBCOLOR_WARN_COLOR="${LIBCOLOR_NORMAL}${LIBCOLOR_CYAN}"
LIBCOLOR_ERROR_COLOR="${LIBCOLOR_BOLD}${LIBCOLOR_RED}"
LIBCOLOR_QUERY_COLOR="${LIBCOLOR_BOLD}${LIBCOLOR_YELLOW}"
LIBCOLOR_FILE_COLOR="${LIBCOLOR_BOLD}${LIBCOLOR_WHITE}"
LIBCOLOR_DIR_COLOR="${LIBCOLOR_BOLD}${LIBCOLOR_GREEN}"
LIBCOLOR_SYMLINK_COLOR="${LIBCOLOR_BOLD}${LIBCOLOR_CYAN}"

#-------------------------------------------------------------------------------
## @param notice message
##
## Prints the given message in "notice" color.
##
#-------------------------------------------------------------------------------
function libcolor_notice() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_NOTICE_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
## @param warning message
##
## Prints the given message in "warn" color.
##
#-------------------------------------------------------------------------------
function libcolor_warn() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_WARN_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
## @param error message
##
## Prints the given error message in "error" color.
##
#-------------------------------------------------------------------------------
function libcolor_error() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_ERROR_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
## @param query message
##
## Prints the given query message in "query" color.
##
#-------------------------------------------------------------------------------
function libcolor_query() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_QUERY_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
## @param file name
##
## Prints the given file name in "file" color.
##
#-------------------------------------------------------------------------------
function libcolor_file() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_FILE_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
## @param directory name
##
## Prints the given directory name in "dir" color.
##
#-------------------------------------------------------------------------------
function libcolor_dir() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_DIR_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
## @param symlink name
##
## Prints the given symlink name in "symlink" color.
##
#-------------------------------------------------------------------------------
function libcolor_symlink() {
  local normal="$LIBCOLOR_NORMAL_COLOR"
  local color="$LIBCOLOR_SYMLINK_COLOR"
  local LIBCOLOR_NORMAL_COLOR="$color"

  if [[ "$LIBCOLOR_NOCOLOR" = "yes" ]]
  then
    echo -n "$@"
  else
    echo -ne "$color"
    echo -n "$@"
    echo -ne "$normal"
  fi
}

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
