SMGL-Release-devel by the Source Mage GNU/Linux team 0e<www.sourcemage.org>07

09Welcome07 to 04Source Mage GNU/Linux07 (Linux kernel 2.4.28)
Copyright (C) 2000-2001 by Kyle Sallee
Copyright (C) 2002-2005 by Source Magers <www.sourcemage.org>
All Rights Reserved

Source Mage is distributed under the terms of the GNU General Public License
Version 2 Please see 01http://www.gnu.org/copyleft/gpl.html07 for the GNU GPL

Download Source Mage GNU/Linux and documentation from
01http://www.sourcemage.org07

* To install Source Mage GNU/Linux right now, just press 02enter07. If
  you need special kernel parameters, just type 02install07 followed by
  kernel parameters, like "acpi=off" for instance.

* This is a TESTING version. Chances are it does not work at all. If 
  you're new to Source Mage, you'll be better off downloading the 
  official latest release, 0.9.3

* This version uses framebuffers. If you get no picture after this 
  screen, try typing 02lowres07 at this prompt.
