SMGL-__SMGL_TEMPLATE_ISO_VERSION__ by the Source Mage GNU/Linux team 0e<www.sourcemage.org>07
This ISO made using @GRIMOIRE_VERSION@.

09Welcome07 to 04Source Mage GNU/Linux07
Copyright (C) 2000-2001 by Kyle Sallee
Copyright (C) 2002-2005 by Source Magers <www.sourcemage.org>
All Rights Reserved

Source Mage is distributed under the terms of the GNU General Public License
Version 2 Please see 01http://www.gnu.org/copyleft/gpl.html07 for the GNU GPL

Download Source Mage GNU/Linux and documentation from
01http://www.sourcemage.org07

* To install Source Mage GNU/Linux right now, just press 02enter07. If
  you need special kernel parameters, just type 02install07 followed by
  kernel parameters, like "acpi=off" for instance.

* Thank you for trying a testing version. Remember, you can get help on IRC
  on irc.freenode.net, channel #sourcemage-cauldron or #sourcemage.
  If you find any bugs, please go to bugs.sourcemage.org and report them, we
  absolutely love feedback.
