#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  Runtime testing harness functionality.
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

function ward_file() {
  local dir="$1"

  [[ -f "$dir" ]] || return 1
}

function ward_dir() {
  local dir="$1"

  [[ -d "$dir" ]] || return 1
}

function ward_symlink() {
  local link="$1"

  [[ -h "$link" ]] || return 1
}

function ward_symlink_file() {
  local link="$1"

  ward_symlink "$link" || return 1

  ward_file "$link" || return 1
}

function ward_symlink_dir() {
  local link="$1"

  ward_symlink "$link" || return 1

  ward_dir "$link" || return 1
}

#-------------------------------------------------------------------------------
## @param base path to sys target (optional)
##
## Tests for the presence of the usr/src/linux symlink, relative to a base path.
## If the base path isn't supplied as the first argument, then it defaults to /
## (root).
##
#-------------------------------------------------------------------------------
function ward_kernel_symlink() {
  local base="$1"

  if ! ward_symlink_dir "$base/usr/src/linux"
  then
    libcolor_error "error: kernel symlink not found in "
    libcolor_file "$base"
  fi
}

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
