#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  Function and variable definitions for the wards.
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

# set LC_COLLATE to C so we don't get affected by the user's locale
# when grepping, sorting, etc.
export LC_COLLATE="C"

# ensure that WARD_PATH has a value
WARD_PATH="${WARD_PATH:-$(dirname $0)}"

# load liberror (this is not optional)
if ! . "$WARD_PATH/../lib/liberror"
then
  echo "error: could not load $WARD_PATH/../lib/liberror"
  exit 1
fi

# load libcolor (there should be an option for this later)
if ! . "$WARD_PATH/../lib/libcolor"
then
  echo "error: could not load $WARD_PATH/../lib/libcolor"
  exit 1
fi

#-------------------------------------------------------------------------------
## @param definition file
## @param source1 [source2 source3...]
##
## Tests whether any variables used in source1 (source2, source3, etc.) are
## defined in the definition file. Any variables that are used but not defined
## in the definition file are output via libcolor_warn, preceded by the file
## they were found in via libcolor_file.
##
#-------------------------------------------------------------------------------
function ward_global_variables() {
  local defines=""
  local file=""

  # get the defines file, then drop it from the argument list
  defines="$1"
  shift

  # make sure the defines file exists, otherwise we can't check anything
  if [[ ! -f "$defines" ]]
  then
    echo "error: definition file not found"
    liberror_die $ERR_FATAL
  fi

  while [[ $# -gt 0 ]]
  do
    file="$1"
    shift

    [[ -f "$file" ]] || continue

    # as per the API specification, all global variables are required to be
    # uppercase, and must begin with a letter, containing only letters,
    # underscores, and trailing numbers
    for search in $(grep -o '${\?[A-Z][A-Z_]*[0-9]*' "$file" | sed 's/^\${\?//' | sort -u)
    do
      if ! grep -q "$search=" "$defines"
      then
        echo "$(libcolor_file $file): $(libcolor_warn $search)"
      fi
    done
  done
}

#-------------------------------------------------------------------------------
## @param error code file
##
## Ensures that the error code file itself is properly defined, making sure that
## for every error code there is a matching error message, and for every error
## message there is a matching error code.
##
#-------------------------------------------------------------------------------
function ward_error_codes() {
  local errorcodes="$1"
  local leader="       "
  local codes=()
  local msgcode=""
  local count=""

  # make sure the defines file exists, otherwise we can't check anything
  if [[ ! -f "$errorcodes" ]]
  then
    libcolor_error "error: error code file "
    libcolor_file "$errorcodes"
    libcolor_error " not found"
    echo ""
    liberror_die $ERR_FATAL
  fi

  if ! source "$errorcodes" 2 > /dev/null
  then
    libcolor_error "error: could not source error code file "
    libcolor_file "$errorcodes"
    echo ""
  fi

  # get the list of defined error codes
  codes=( $(grep -o '^ERR_[A-Z_]\+[0-9]*' "$errorcodes" | grep -v 'ERR_MSGS') )

  # test if the number of messages matches the number of error codes
  if [[ "${#codes[@]}" -ne "${#ERR_MSGS[@]}" ]]
  then
    libcolor_error "error: "
    libcolor_error "number of error codes not equal to number of messages"
    echo ""
    libcolor_error "${leader}codes:    ${#codes[@]}"
    echo ""
    libcolor_error "${leader}messages: ${#ERR_MSGS[@]}"
    echo ""
  fi

  # for every error code defined, make sure there is a corresponding message
  for ((count=0; "$count" < "${#codes[@]}"; count++))
  do
    if ! grep -q "${codes[count]}\$" "$errorcodes"
    then
      libcolor_error "error: ${codes[count]}: "
      libcolor_error "DEFINED but has no corresponding message"
      echo ""
    fi
  done

  # for every error message defined, make sure there is a corresponding code
  for ((count=0; "$count" < "${#ERR_MSGS[@]}"; count++))
  do
    msgcode=$(grep "${ERR_MSGS[count]}.*# " "$errorcodes" | sed 's/.*# //')

    if ! grep -q "^${msgcode}=" "$errorcodes"
    then
      libcolor_error "error: $msgcode: "
      libcolor_error "NOT DEFINED but message is"
      echo ""
    fi
  done
}

#-------------------------------------------------------------------------------
## @param directory where function definition files are stored
## @param source1 [source2 source3...]
##
## Tests whether any functions used in source1 (source2, source3, etc.) are
## defined. Any functions that are used but not defined in the corresponding
## definition file are output via libcolor_warn, preceded by the file they were
## found in via libcolor_file.
##
#-------------------------------------------------------------------------------
function ward_functions() {
  local path=""
  local file=""
  local prefix=""
  local list=""
  local matched=""

  # make sure we have a minimum number of arguments
  if [[ $# -lt 2 ]]
  then
    echo "error: improper number of arguments"
    liberror_die $ERR_FATAL
  fi

  # get the defines file, then drop it from the argument list
  path="$1"
  shift

  # make sure we got a good path component
  if [[ ! -d "$WARD_PATH/../$path" ]]
  then
    echo "error: library search path not recognized"
    liberror_die $ERR_FATAL
  else
    path="$WARD_PATH/../$path"
  fi

  while [[ $# -gt 0 ]]
  do
    file="$1"
    shift

    [[ -f "$file" ]] || continue

    list=($(grep -o "^[ ]*[a-z]\+_[a-z_]\+" "$file" | sed 's/^ *//' | sort -u))
    # for each called function, check prefix by prefix
    for function in "${list[@]}"
    do
      # check if the function is defined somewhere in the file it came from
      grep -q "^function $function() {" "$file" && continue

      # seed the defines variable for the loop below
      local mangle="$function"

      # check against the prefixes, one at a time
      while $(echo $mangle | grep -q '^[a-z]\+_[a-z_]\+')
      do
        prefix="${mangle%%_*}"
        [[ "$prefix" == "enchant" ]] && prefix="enchantment"

        # check for the function in a library file matching the prefix
        if [[ -f "$path/lib$prefix" ]]
        then
          if grep -q "^function $function() {" "$path/lib$prefix"
          then
            matched="yes"
            break
          fi
        elif [[ -f "$path/lib.$prefix" ]]
        then
          if grep -q "^function $function() {" "$path/lib.$prefix"
          then
            matched="yes"
            break
          fi
        fi

        # no match yet, strip the prefix and repeat
        mangle="${mangle#*_}"
      done

      # if the function isn't defined in the corresponding file, warn the user
      if [[ -z "$matched" ]]
      then
        echo "$(libcolor_file $file): $(libcolor_warn $function)"
      fi
    done
  done
}

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
