#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  Function and variable definitions for the wards.
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

# set LC_COLLATE to C so we don't get affected by the user's locale
# when grepping, sorting, etc.
export LC_COLLATE="C"

# shorthand and non-hardcoded /dev/null for output dumping
WARD_NULL="${WARD_NULL:-/dev/null}"

# ensure that WARD_PATH has a value
WARD_PATH="${WARD_PATH:-$(dirname $0)}"

WARD_LIB_PATH="${WARD_LIB_PATH:-$WARD_PATH/../lib}"

#-------------------------------------------------------------------------------
##
## Used only when checking initialization of the library and a fatal error
## occurs. Afterwards, functions from liberror are used instead.
##
#-------------------------------------------------------------------------------
function ward_fatal_error() {
  echo "$1"
  exit 1
}

# load liberror (this is not optional)
. "$WARD_LIB_PATH/liberror" 2>"$WARD_NULL" ||
  ward_fatal_error "error: could not load $WARD_LIB_PATH/liberror"

# load libcolor (there should be an option for this later)
. "$WARD_LIB_PATH/libcolor" 2>"$WARD_NULL" ||
  ward_fatal_error "error: could not load $WARD_LIB_PATH/libcolor"

unset ward_fatal_error

# test/set whether color output should be enabled
[[ $WARD_COLOR != "yes" ]] && LIBCOLOR_NOCOLOR="yes"

#-------------------------------------------------------------------------------
## @param library name to load (no path, just basename)
##
## Loads the library given as the first argument. liberror_check_fatal is
## called to check if there was a problem loading the library, and if there was
## it will print a corresponding error message and then exit with the error
## $ERR_LOAD_LIBRARY.
##
#-------------------------------------------------------------------------------
function ward_load_library() {
  local lib="$1"

  . "$WARD_PATH/$lib" 2>$WARD_NULL
  liberror_check_fatal
}

#-------------------------------------------------------------------------------
# ward includes
#-------------------------------------------------------------------------------
ward_load_library "libsource"
ward_load_library "libruntime"

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
