#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  This goes through all the known sources for both cauldron and enchantment,
##  scans their uses of global configurable variables (those listed in the
##  etc/ config files), and ensures that they are defined in the relevant
##  config files.
##
##=head1 COPYRIGHT
##
##  Copyright 2010 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------


WARD_PATH="${WARD_PATH:-$(dirname $0)}"

if ! . "$WARD_PATH/libward"
then
  echo "error: could not load $WARD_PATH/libward"
  exit 1
fi

# source the list of cauldron source files to examine
if ! . "$WARD_PATH/cauldron_sources"
then
  echo "error: could not load cauldron_sources"
  exit $ERR_FATAL
fi
# source the list of enchantment source files to examine
if ! . "$WARD_PATH/enchantment_sources"
then
  echo "error: could not load enchantment_sources"
  exit $ERR_FATAL
fi

function ward_print_usage() {
  cat << EndUsage
Usage: $(basename $0) [-n]

Calls the functions delinter to check whether there are functions called in the
known cauldron and enchantment source files that aren't defined in the
respective library files. If passed -n, color output is disabled.
EndUsage
}

function ward_usage() {
  ward_print_usage
  exit $ERR_FATAL
}

while [[ "$#" -gt 0 ]]
do
  case "$1" in
    # check if color should be disabled
    "-n")
      LIBCOLOR_NOCOLOR="yes"
      ;;
    # check if the user only wants to process cauldron
    "cauldron")
      PROCESS_ENCHANTMENT="no"
      ;;
    # check if the user only wants to process enchantment
    "enchantment")
      PROCESS_CAULDRON="no"
      ;;
    # unknown argument
    *)
      ward_print_usage
      ;;
  esac
  shift
done

PROCESS_CAULDRON="${PROCESS_CAULDRON:-yes}"
PROCESS_ENCHANTMENT="${PROCESS_ENCHANTMENT:-yes}"

if [[ "$PROCESS_CAULDRON" == "yes" ]]
then
  ward_get_sources "cauldron_sources"
  cauldron="$WARD_PATH/../cauldron"

  # check cauldron files
  libcolor_notice "Checking cauldron functions"
  echo ""
  ward_functions -p "$cauldron" -l "$cauldron/lib" "${sources[@]}"
fi

if [[ "$PROCESS_ENCHANTMENT" == "yes" ]]
then
  ward_get_sources "enchantment_sources"
  enchantment="$WARD_PATH/../enchantment"

  # check enchantment files
  libcolor_notice "Checking enchantment functions"
  echo ""
  ward_functions -p "$enchantment" -l "$enchantment/lib" "${sources[@]}"
fi

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
