#!/bin/bash 

# a script to be run as the start of a chroot to dispel all the things
# in the ISO chroot that aren't strictly needed to boot a system

# TODO: need to set up a way to return true from this correctly
# shouldn't always fail if it failed to find a spell to dispel.
dispel --nosustain gcc autoconf automake bison flex installwatch make sorcery-pubkeys bin86 elvis 

# always want success at the moment
exit 0
