#!/bin/bash


# !!!!! REMEMBER /VAR/SPOOL/SORCERY IS BIND MOUNTED !!!!!

# second stage of the ISO. 

#add a few more spells 
cast man

# generate the initrd
cd /root
./mkinitrd
cp /root/initrd* /boot/.

#cat /boot/initrd.size into the /isolinux/isolinux.cfg file
sed -i -e "s/@INITRD_SIZE@/$(cat /boot/initrd.size)/" /isolinux/isolinux.cfg

# set up the boot directory so that isolinux can boot it
cd /boot
rm vmlinuz config boot System.map
mv System.map* System.map
mv config-* config
mv vmlinuz-* linux

# dispel a bunch of stuff we don't need
dispel --nosustain gcc autoconf automake bison flex installwatch
dispel --nosustain g++ make sorcery-pubkeys bin86 perl elvis

#clean out extra files of uselessness
rm -rf /var/cache/sorcery/*
rm -rf /usr/src/*

# remove my downloading information
rm /etc/resolv.conf

# destroy useless things on the ISO
rm -rf /var/state/sorcery/*
rm -rf /var/lib/sorcery/codex/*

# remove static libs
find /lib -name '*.a' -delete
