#!/bin/sh
umount /initrd/dev/pts 2> /dev/null
umount /initrd/dev/shm 2> /dev/null
umount /initrd/dev 2> /dev/null
umount /initrd/sys 2> /dev/null
umount /initrd/proc 2> /dev/null
umount /initrd/var/run 2> /dev/null
umount /initrd/var/lock 2> /dev/null
umount /initrd 2> /dev/null
/sbin/blockdev --flushbufs /dev/ram0
