SMGL-__SMGL_TEMPLATE_ISO_VERSION__ by the Source Mage GNU/Linux team <www.sourcemage.org>

Welcome to Source Mage GNU/Linux
Copyright (C) 2000-2001 by Kyle Sallee
Copyright (C) 2002-2005 by Source Magers <www.sourcemage.org>
All Rights Reserved

Source Mage is distributed under the terms of the GNU General Public License
Version 2 Please see http://www.gnu.org/copyleft/gpl.html for the GNU GPL

Download Source Mage GNU/Linux and documentation from
http://www.sourcemage.org

* To install Source Mage GNU/Linux right now, just press 'enter'. If
  you need special kernel parameters, just type 'install' followed by
  kernel parameters, like "acpi=off" for instance.

* Thank you for trying a testing version. Remember, you can get help on IRC
  on irc.freenode.net, channel #sourcemage-cauldron or #sourcemage.
  If you find any bugs, please go to bugs.sourcemage.org and report them, we
  absolutely love feedback.
