#!/bin/sh

# Author : Benoit PAPILLAULT <benoit.papillault@free.fr>
# Creation : 2004/09/22

# Install sorcery stable + stable grimoire in $IMAGE

# we use $IMAGE if defined, or else work/image-stage3
if [ -z "${IMAGE}" ]; then
    IMAGE="work/image-stage3"
fi
echo "using IMAGE=${IMAGE}"

# install sorcery
rm -rf "${IMAGE}/root/tmp" &&
mkdir -p "${IMAGE}/root/tmp" &&
cat sorcery-stable.tar.bz2 | (cd "${IMAGE}/root/tmp" && tar jxf -) &&
echo "installing sorcery" &&
mount --bind /dev "${IMAGE}/dev" &&
chroot "${IMAGE}" sh -c "cd /root/tmp/sorcery; ./install" > /dev/null &&
umount "${IMAGE}/dev" &&
rm -rf "${IMAGE}/root/tmp" &&

# install grimoire

# scribe add stable from file:/root/stable.tar.bz2 is not the proper
# way to do it since the system remembers the file location.

echo "installing stable grimoire" &&
rm -rf "${IMAGE}/var/lib/sorcery/codex/stable" &&
mkdir -p "${IMAGE}/var/lib/sorcery/codex" &&
cat stable.tar.bz2 | (cd "${IMAGE}/var/lib/sorcery/codex" && tar jxf -) &&

# changing some files
echo "GRIMOIRE_DIR[0]=/var/lib/sorcery/codex/stable" > \
  "${IMAGE}/etc/sorcery/local/grimoire" &&
echo "FROM_URL=http://codex.sourcemage.org/stable.tar.bz2" > \
  "${IMAGE}/var/lib/sorcery/codex/stable/GRIMOIRE" &&
mount --bind /dev "${IMAGE}/dev" &&
chroot "${IMAGE}" scribe reindex &&
umount "${IMAGE}/dev"
