#!/bin/bash
#-------------------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
##  These are the cauldron-specific error definitions.
##
##=head1 COPYRIGHT
##
##  Copyright 2009 by the Cauldron Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# ERROR definitions
#-------------------------------------------------------------------------------

# base error codes
liberror_add_error ERR_MK_DIR "could not make directory"
liberror_add_error ERR_DIR_EXISTS "directory already exists"
liberror_add_error ERR_FILE_ACCESS "file not accessible"
liberror_add_error ERR_DIR_ACCESS "directory not accessible"
liberror_add_error ERR_CP_FILE "could not copy file"
liberror_add_error ERR_CHMOD_FILE "could not chmod file"
liberror_add_error ERR_RM_FILES "could not remove files"
liberror_add_error ERR_TARGET "invalid target parameter"

# libcauldron base
liberror_add_error ERR_LOAD_LIBRARY "problem loading library"
liberror_add_error ERR_CLEANUP_BUILD "could not clean up build directory"
liberror_add_error ERR_CLEANUP_TMP "could not clean up temporary directory"

# libcauldron build
liberror_add_error ERR_UNPACK_CACHE \
  "could not unpack spell cache inside build directory"
liberror_add_error ERR_RM_CACHE \
  "could not remove spell cache after unpacking in build"
liberror_add_error ERR_HOST_TRIPLE "could not get host triple for builds"
liberror_add_error ERR_BUILD_SPOOL "build directory sorcery spool does not exist"
liberror_add_error ERR_RESOLV "resolv.conf missing in the build directory"

# libcauldron cleaner files
liberror_add_error ERR_CLEAN_CLEANER "cleaner files could not be found"
liberror_add_error ERR_CLEAN_DIR "failed to clean directory from iso"
liberror_add_error ERR_CLEAN_FILE "failed to clean file from iso"

# libcauldron enchantment
liberror_add_error ERR_ENCHANT_CONFIG "could not source enchant config"
liberror_add_error ERR_INSTALLER_DIR \
  "could not create the iso installer directory"
liberror_add_error ERR_COPY_INSTALLER "could not copy installer to iso"
liberror_add_error ERR_LINK_INSTALLER "could not link installer in iso"

# libcauldron final product
liberror_add_error ERR_ISO_PACKAGE "could not create final iso file"
liberror_add_error ERR_ISO_COMPRESS "could not compress final iso file"
liberror_add_error ERR_SYS_PACKAGE "could not package final sys file"
liberror_add_error ERR_SYS_COMPRESS "could not compress final sys archive"

# lib.chroot
liberror_add_error ERR_CHROOT_UNDEF "chroot target is undefined"
liberror_add_error ERR_CHROOT_INIT "could not init chroot"
liberror_add_error ERR_CHROOT_DONE "could not close chroot"
liberror_add_error ERR_CHROOT_CURRENT "chroot not current or not defined"
liberror_add_error ERR_CHROOT_EXEC "could not execute chroot command"
liberror_add_error ERR_CHROOT_CAST "chroot cast failed"
liberror_add_error ERR_CHROOT_DISPEL "chroot dispel failed"
liberror_add_error ERR_CHROOT_REBUILD "chroot rebuild failed"

# lib.init
liberror_add_error ERR_INIT_INSTALL_RAMFS \
  "problem installing built initramfs into iso"
liberror_add_error ERR_INIT_INSTALL_RD \
  "problem installing built initramdisk into iso"
liberror_add_error ERR_INIT_MAKE_RAMFS "could not build initramfs"
liberror_add_error ERR_INIT_MAKE_RD "could not build initramdisk"
liberror_add_error ERR_INIT_MAKE_FS \
  "could not make filesystem for initramfs/ramdisk"

# lib.sorcerous
liberror_add_error ERR_SORCEROUS_ARCHIVE \
  "target sorcery not set to archive casts"
liberror_add_error ERR_SORCEROUS_TARGET "target sorcery files not found"
liberror_add_error ERR_SORCEROUS_HOST "host sorcery not found"
liberror_add_error ERR_SORCEROUS_CREATE_CACHE "could not create spell cache"
liberror_add_error ERR_SORCEROUS_ISO_SORCERY_CONFIG \
  "could not create local sorcery config directory in iso"
liberror_add_error ERR_SORCEROUS_DOWNLOAD "could not download sorcery"
liberror_add_error ERR_SORCEROUS_UNPACK \
  "could not unpack a valid sorcery install"
liberror_add_error ERR_SORCEROUS_INSTALL \
  "could not install sorcery into build directory"

# lib.toolchain
liberror_add_error ERR_TOOLCHAIN_CP_CACHE \
  "could not copy toolchain spell cache from host system into build directory"
liberror_add_error ERR_TOOLCHAIN_BUILD_CACHE \
  "could not build toolchain cache file from spell install info"
liberror_add_error ERR_TOOLCHAIN_STAGE1 \
  "cross-toolchain stage 1 failed"
liberror_add_error ERR_TOOLCHAIN_STAGE2 \
  "cross-toolchain stage 2 failed"
liberror_add_error ERR_TOOLCHAIN_STAGE3 \
  "cross-toolchain stage 3 failed"
liberror_add_error ERR_TOOLCHAIN_CAST \
  "could not cast toolchain spell cache"
liberror_add_error ERR_TOOLCHAIN_DISPEL \
  "could not dispel toolchain spell cache"
liberror_add_error ERR_TOOLCHAIN_GATHER \
  "could not generate toolchain spell cache"
liberror_add_error ERR_TOOLCHAIN_SORCERY \
  "sorcery not found in toolchain root"
liberror_add_error ERR_TOOLCHAIN_RESURRECT \
  "could not resurrect spell using sorcery"
liberror_add_error ERR_TOOLCHAIN_COMPILER_TEST \
  "could not compile a functioning binary using the chroot compiler"
liberror_add_error ERR_TOOLCHAIN_BASEROOT_TEST \
  "the basesystem chroot failed the validity test"
liberror_add_error ERR_TOOLCHAIN_BASEROOT \
  "could not acquire and set up a valid basesystem chroot"

#-------------------------------------------------------------------------------
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#-------------------------------------------------------------------------------

# vim:ai:tw=80:tabstop=2:softtabstop=2:shiftwidth=2:expandtab
