#!/bin/sh

# Author : Benoit PAPILLAULT <benoit.papillault@free.fr>
# Creation : 26/05/2003

if [ $# -ne 1 ]; then
	echo "usage: $0 smgl.iso";
	exit -1;
fi

ISO="$1"

mkdir -p /mnt/iso

# umount previously mounted /mnt/iso if any
umount /mnt/iso

echo "mounting ISO image..."
mount -o loop "${ISO}" /mnt/iso

# since we need to modify some files, copy the whole directory

rm -rf /mnt/iso2
mkdir -p /mnt/iso2

echo "copying ISO image..."
(cd /mnt/iso ; tar cfl - . ) | ( cd /mnt/iso2 ; tar xfp - )

# make the new ISO

cd /mnt/iso2

# removing the rr_moved directory
rmdir rr_moved

echo "creatig a new ISO image..."
mkisofs \
    -b isolinux/isolinux.bin -c isolinux/boot.cat \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -R -o /home/gravage_cd/smgl-new.iso .

echo "Done."

